// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED


// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS


// ================================================================================
//#MARKER ADD SHAPED

mods.avaritia.ExtremeCrafting.addShaped (<Botania:blackLotus:1>,
[[<Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>],
  [<Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>],
  [<magicalcrops:NatureEssence>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <universalsingularities:universal.extraPlanets.singularity:1>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>,<magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>]]);

mods.avaritia.ExtremeCrafting.addShaped (<Botania:blackLotus:1>,
[[<Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>],
  [<Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>],
  [<magicalcrops:NatureEssence>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <universalsingularities:universal.vanilla.singularity>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <Botania:blackLotus>, <Botania:blackLotus>, <Botania:blackLotus>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>]]);

mods.avaritia.ExtremeCrafting.addShaped (<Botania:blackLotus>,
[[<Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>],
  [<Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>],
  [<magicalcrops:NatureEssence>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <universalsingularities:universal.vanilla.singularity>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>]]);

mods.avaritia.ExtremeCrafting.addShaped (<Botania:blackLotus>,
[[<Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>],
  [<Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>],
  [<magicalcrops:NatureEssence>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <universalsingularities:universal.extraPlanets.singularity:1>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <Botania:petalBlock:15>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>],
  [<magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <GalacticraftMars:tile.cavernVines>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>, <magicalcrops:NatureEssence>]]);

mods.avaritia.ExtremeCrafting.addShaped (<chancecubes:Chance_Icosahedron>,
[[<ore:blockPlastic>, <Botania:blackLotus:1>, <Botania:blackLotus:1>, <Botania:blackLotus:1>, <chisel:beacon:15>, <ore:manaPearl>, <ore:manaPearl>, <ore:manaPearl>, <ore:blockPlastic>],
  [<Botania:pool:3>, <ore:cloud>, <Botania:bifrostPerm>, <Botania:bifrostPerm>, <Avaritia:Endest_Pearl>, <Botania:bifrostPerm>, <Botania:bifrostPerm>, <ore:cloud>, <Botania:manaResource:14>],
  [<Botania:pool:3>, <Botania:bifrostPerm>, <ProjectE:nova_catalyst>, <evilcraft:weatherContainer:1>, <ore:blockPrismarine>, <evilcraft:weatherContainer:1>, <ProjectE:nova_cataclysm>, <Botania:bifrostPerm>, <Botania:manaResource:14>],
  [<Botania:pool:3>, <Botania:bifrostPerm>, <evilcraft:weatherContainer:1>, <ore:blockPlastic>, <Botania:lightRelay>, <ore:blockPlastic>, <evilcraft:weatherContainer:1>, <Botania:bifrostPerm>, <Botania:manaResource:14>],
  [<chisel:beacon:15>, <Avaritia:Cosmic_Meatballs>, <ore:blockPrismarine>, <ore:blockPrismarine>, <ExtraUtilities:unstableingot:2>, <ore:blockPrismarine>, <ore:blockPrismarine>, <eternalsingularity:eternal_singularity>, <chisel:beacon:15>],
  [<Botania:manaResource:14>, <Botania:bifrostPerm>, <evilcraft:weatherContainer:1>, <ore:blockPlastic>, <Botania:lightRelay:1>, <ore:blockPlastic>, <evilcraft:weatherContainer:1>, <Botania:bifrostPerm>, <Botania:pool:3>],
  [<Botania:manaResource:14>, <Botania:bifrostPerm>, <evilcraft:lightningBomb>, <evilcraft:weatherContainer:1>, <ore:blockPrismarine>, <evilcraft:weatherContainer:1>, <ore:foodChaoscookie>, <Botania:bifrostPerm>, <Botania:pool:3>],
  [<Botania:manaResource:14>, <ore:cloud>, <Botania:bifrostPerm>, <Botania:bifrostPerm>, <Avaritia:Ultimate_Stew>, <Botania:bifrostPerm>, <Botania:bifrostPerm>, <ore:cloud>, <Botania:pool:3>],
  [<ore:blockPlastic>, <ore:manaPearl>, <ore:manaPearl>, <ore:manaPearl>, <chisel:beacon:15>, <Botania:blackLotus:1>, <Botania:blackLotus:1>, <Botania:blackLotus:1>, <ore:blockPlastic>]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_transmutation_tablet>,
[[<ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>],
  [<ExtraPlanets:tier4Items:4>, <Avaritia:Singularity:1>, <ThermalExpansion:material:1>, <Railcraft:borehead.diamond>, <Railcraft:borehead.steel>, <Railcraft:borehead.iron>, <rftools:redstoneReceiverBlock>, <Avaritia:Singularity:3>, <ExtraPlanets:tier4Items:4>],
  [<ExtraPlanets:tier4Items:4>, <ExtraUtilities:generator.64:4>, <Avaritia:Singularity:1>, <aether:zaniteGemstone>, <universalsingularities:universal.vanilla.singularity:1>, <aether:zaniteGemstone>, <Avaritia:Singularity:3>, <ExtraUtilities:generator.64:9>, <ExtraPlanets:tier4Items:4>],
  [<ExtraPlanets:tier4Items:4>, <MineFactoryReloaded:machine.1:15>, <Thaumcraft:blockEssentiaReservoir>, <evilcraft:burningGemStone>, <Botania:manaTablet>, <evilcraft:burningGemStone>, <Thaumcraft:ItemResource:14>, <enderioaddons:itemModule:9>, <ExtraPlanets:tier4Items:4>],
  [<ExtraPlanets:tier4Items:4>, <avaritiaddons:ExtremeAutoCrafter>, <ProjectE:condenser_mk2>, <universalsingularities:universal.vanilla.singularity:1>, <ProjectE:transmutation_table>, <universalsingularities:universal.vanilla.singularity:1>, <ProjectE:condenser_mk2>, <avaritiaddons:ExtremeAutoCrafter>, <ExtraPlanets:tier4Items:4>],
  [<ExtraPlanets:tier4Items:4>, <MineFactoryReloaded:machine.1:15>, <Thaumcraft:blockEssentiaReservoir>, <Botania:openCrate:1>, <Botania:pool:3>, <Botania:openCrate:1>, <Thaumcraft:ItemResource:14>, <enderioaddons:itemModule:9>, <ExtraPlanets:tier4Items:4>],
  [<ExtraPlanets:tier4Items:4>, <ExtraUtilities:generator.64:11>, <universalsingularities:universal.tinkersConstruct.singularity:6>, <evilcraft:exaltedCrafter:3>, <universalsingularities:universal.vanilla.singularity:1>, <evilcraft:exaltedCrafter:2>, <Avaritia:Singularity:2>, <ExtraUtilities:generator.64:7>, <ExtraPlanets:tier4Items:4>],
  [<ExtraPlanets:tier4Items:4>, <universalsingularities:universal.tinkersConstruct.singularity:6>, <EnderIO:blockWirelessCharger>, <appliedenergistics2:item.ToolWirelessTerminal>, <appliedenergistics2:tile.BlockWireless>, <appliedenergistics2:item.ItemMultiMaterial:42>, <EnderIO:blockWirelessCharger>, <Avaritia:Singularity:2>, <ExtraPlanets:tier4Items:4>],
  [<ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>, <ExtraPlanets:tier4Items:4>]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:transmutation_table>,
[[<ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>],
  [<ore:ingotCarbon>, <ore:gemYellowDiamond>, <ImmersiveEngineering:metalDevice:13>, <appliedenergistics2:tile.BlockController>, <rftools:redstoneTransmitterBlock>, <appliedenergistics2:item.ItemMultiPart:360>, <ImmersiveEngineering:metalDevice:13>, <ore:gemRedDiamond>, <ore:ingotCarbon>],
  [<ore:ingotCarbon>, <ImmersiveEngineering:metalDevice:13>, <ore:gemYellowDiamond>, <ProjectE:item.pe_fuel:2>, <ore:gemGreenDiamond>, <ProjectE:item.pe_fuel:2>, <ore:gemRedDiamond>, <ImmersiveEngineering:metalDevice:13>, <ore:ingotCarbon>],
  [<ore:ingotCarbon>, <BuildCraft|Builders:libraryBlock>, <ProjectE:item.pe_fuel:2>, <universalsingularities:universal.extraTiC.singularity>, <Botania:sparkUpgrade:1>, <universalsingularities:universal.extraTiC.singularity>, <ProjectE:item.pe_fuel:2>, <QuantumStorage:quantumdsu>, <ore:ingotCarbon>],
  [<ore:ingotCarbon>, <avaritiaddons:ExtremeAutoCrafter>, <ore:gemGreenDiamond>, <Botania:sparkUpgrade:1>, <universalsingularities:universal.bigReactors.singularity:3>, <Botania:sparkUpgrade:1>, <ore:gemGreenDiamond>, <avaritiaddons:ExtremeAutoCrafter>, <ore:ingotCarbon>],
  [<ore:ingotCarbon>, <MineFactoryReloaded:machine.1:3>, <ProjectE:item.pe_fuel:2>, <universalsingularities:universal.extraTiC.singularity>, <Botania:sparkUpgrade:1>, <universalsingularities:universal.extraTiC.singularity>, <ProjectE:item.pe_fuel:2>, <MineFactoryReloaded:machine.1:3>, <ore:ingotCarbon>],
  [<ore:ingotCarbon>, <ImmersiveEngineering:metalDevice:13>, <ore:gemPurpleDiamond>, <ProjectE:item.pe_fuel:2>, <ore:gemGreenDiamond>, <ProjectE:item.pe_fuel:2>, <ore:gemBlueDiamond>, <ImmersiveEngineering:metalDevice:13>, <ore:ingotCarbon>],
  [<ore:ingotCarbon>, <ore:gemPurpleDiamond>, <ImmersiveEngineering:metalDevice:13>, <evilcraft:burningGemStone>, <ThermalExpansion:material:2>, <evilcraft:burningGemStone>, <ImmersiveEngineering:metalDevice:13>, <ore:gemBlueDiamond>, <ore:ingotCarbon>],
  [<ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>, <ore:ingotCarbon>]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:condenser_mk2>,
[[<ProjectE:item.pe_covalence_dust>, <ProjectE:item.pe_covalence_dust:1>, <ProjectE:item.pe_covalence_dust:2>, <Botania:storage:1>, <ExtraPlanets:tier4Items:11>, <Botania:storage:1>, <ProjectE:item.pe_covalence_dust>, <ProjectE:item.pe_covalence_dust:1>, <ProjectE:item.pe_covalence_dust:2>],
  [<thermsingul:ThermalSingularity>, <thermsingul:ThermalSingularity>, <thermsingul:ThermalSingularity>, <ProjectE:item.pe_matter:1>, <ExtraPlanets:tier4Items:11>, <ProjectE:item.pe_matter:1>, <thermsingul:ThermalSingularity>, <thermsingul:ThermalSingularity>, <thermsingul:ThermalSingularity>],
  [<universalsingularities:universal.bigReactors.singularity>, <universalsingularities:universal.bigReactors.singularity>, <universalsingularities:universal.bigReactors.singularity>, <Botania:storage:1>, <ExtraPlanets:tier4Items:11>, <Botania:storage:1>, <universalsingularities:universal.bigReactors.singularity>, <universalsingularities:universal.bigReactors.singularity>, <universalsingularities:universal.bigReactors.singularity>],
  [<universalsingularities:universal.bigReactors.singularity:1>, <universalsingularities:universal.bigReactors.singularity:1>, <universalsingularities:universal.bigReactors.singularity:1>, <ProjectE:item.pe_matter:1>, <ExtraPlanets:tier4Items:11>, <ProjectE:item.pe_matter:1>, <universalsingularities:universal.bigReactors.singularity:1>, <universalsingularities:universal.bigReactors.singularity:1>, <universalsingularities:universal.bigReactors.singularity:1>],
  [<rftools:inventoryPlusModuleItem>, <ProjectE:condenser_mk1>, <EnderIO:blockInventoryPanel>, <Botania:storage:1>, <ExtraPlanets:tier4Items:11>, <Botania:storage:1>, <EnderIO:blockInventoryPanel>, <ProjectE:condenser_mk1>, <rftools:inventoryPlusModuleItem>],
  [<universalsingularities:universal.enderIO.singularity:4>, <universalsingularities:universal.enderIO.singularity:4>, <universalsingularities:universal.enderIO.singularity:4>, <ProjectE:item.pe_matter:1>, <ExtraPlanets:tier4Items:11>, <ProjectE:item.pe_matter:1>, <universalsingularities:universal.enderIO.singularity:4>, <universalsingularities:universal.enderIO.singularity:4>, <universalsingularities:universal.enderIO.singularity:4>],
  [<universalsingularities:universal.general.singularity:14>, <universalsingularities:universal.general.singularity:14>, <universalsingularities:universal.general.singularity:14>, <Botania:storage:1>, <ExtraPlanets:tier4Items:11>, <Botania:storage:1>, <universalsingularities:universal.general.singularity:14>, <universalsingularities:universal.general.singularity:14>, <universalsingularities:universal.general.singularity:14>],
  [<universalsingularities:universal.vanilla.singularity:1>, <universalsingularities:universal.vanilla.singularity:1>, <universalsingularities:universal.vanilla.singularity:1>, <ProjectE:item.pe_matter:1>, <ExtraPlanets:tier4Items:11>, <ProjectE:item.pe_matter:1>, <universalsingularities:universal.vanilla.singularity:1>, <universalsingularities:universal.vanilla.singularity:1>, <universalsingularities:universal.vanilla.singularity:1>],
  [<rftools:spaceProjectorBlock>, <rftools:matterTransmitterBlock>, <rftools:shieldBlock>, <Botania:storage:1>, <ExtraPlanets:tier4Items:11>, <Botania:storage:1>, <rftools:shieldBlock>, <rftools:matterReceiverBlock>, <rftools:spaceProjectorBlock>]]);

mods.avaritia.ExtremeCrafting.addShaped (<avaritiaddons:ExtremeAutoCrafter>,
 [[<ore:blockCrystal>, <universalsingularities:universal.enderIO.singularity:5>, <universalsingularities:universal.enderIO.singularity:5>, <universalsingularities:universal.enderIO.singularity:5>, <universalsingularities:universal.enderIO.singularity:5>, <universalsingularities:universal.enderIO.singularity:5>, <universalsingularities:universal.enderIO.singularity:5>, <universalsingularities:universal.enderIO.singularity:5>, <ore:blockCrystal>],
  [<Avaritia:Crystal_Matrix>, <appliedenergistics2:tile.BlockCellWorkbench>, <appliedenergistics2:tile.BlockCellWorkbench>, <ore:blockCrystal>, <TConstruct:heavyPlate:500>, <ore:blockCrystal>, <appliedenergistics2:tile.BlockCellWorkbench>, <appliedenergistics2:tile.BlockCellWorkbench>, <Avaritia:Crystal_Matrix>],
  [<ore:blockCrystal>, null, null, <ore:blockCrystal>, <TConstruct:heavyPlate:500>, <ore:blockCrystal>, null, null, <ore:blockCrystal>],
  [<ore:blockCrystal>, <rftools:crafterBlock3>, null, <ore:blockCrystal>, <TConstruct:heavyPlate:500>, <ore:blockCrystal>, null, <rftools:crafterBlock3>, <ore:blockCrystal>],
  [<Avaritia:Crystal_Matrix>, <Avaritia:Dire_Crafting>, <BuildCraft|Factory:autoWorkbenchBlock>, <ore:blockCrystal>, <Avaritia:Resource:5>, <ore:blockCrystal>, <BuildCraft|Factory:autoWorkbenchBlock>, <Avaritia:Dire_Crafting>, <Avaritia:Crystal_Matrix>],
  [<ore:blockCrystal>, <rftools:crafterBlock3>, null, <ore:blockCrystal>, <TConstruct:heavyPlate:500>, <ore:blockCrystal>, null, <rftools:crafterBlock3>, <ore:blockCrystal>],
  [<ore:blockCrystal>, null, null, <ore:blockCrystal>, <TConstruct:heavyPlate:500>, <ore:blockCrystal>, null, null, <ore:blockCrystal>],
  [<Avaritia:Crystal_Matrix>, null, null, <ore:blockCrystal>, <TConstruct:heavyPlate:500>, <ore:blockCrystal>, null, null, <Avaritia:Crystal_Matrix>],
  [<ore:blockCrystal>, <enderioaddons:blockCobbleworks>, <enderioaddons:blockCobbleworks>, <ore:blockCrystal>, <TConstruct:heavyPlate:500>, <ore:blockCrystal>, <enderioaddons:blockCobbleworks>, <enderioaddons:blockCobbleworks>, <ore:blockCrystal>]]);

mods.avaritia.ExtremeCrafting.addShaped (<minecraft:bedrock>,
 [[<ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>],
  [<ExtraUtilities:block_bedrockium>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <ExtraUtilities:block_bedrockium>],
  [<ExtraUtilities:block_bedrockium>, <Avaritia:Resource:2>, <ore:ingotVoid>, <Avaritia:Resource:3>, <Avaritia:Resource:3>, <Avaritia:Resource:3>, <ore:ingotVoid>, <Avaritia:Resource:2>, <ExtraUtilities:block_bedrockium>],
  [<ExtraUtilities:block_bedrockium>, <Avaritia:Resource:2>, <Avaritia:Resource:3>, <ore:ingotVoid>, <ore:ingotCosmicNeutronium>, <ore:ingotVoid>, <Avaritia:Resource:3>, <Avaritia:Resource:2>, <ExtraUtilities:block_bedrockium>],
  [<ExtraUtilities:block_bedrockium>, <Avaritia:Resource:2>, <Avaritia:Resource:3>, <ore:ingotCosmicNeutronium>, <ProjectE:item.pe_matter>, <ore:ingotCosmicNeutronium>, <Avaritia:Resource:3>, <Avaritia:Resource:2>, <ExtraUtilities:block_bedrockium>],
  [<ExtraUtilities:block_bedrockium>, <Avaritia:Resource:2>, <Avaritia:Resource:3>, <ore:ingotVoid>, <ore:ingotCosmicNeutronium>, <ore:ingotVoid>, <Avaritia:Resource:3>, <Avaritia:Resource:2>, <ExtraUtilities:block_bedrockium>],
  [<ExtraUtilities:block_bedrockium>, <Avaritia:Resource:2>, <ore:ingotVoid>, <Avaritia:Resource:3>, <Avaritia:Resource:3>, <Avaritia:Resource:3>, <ore:ingotVoid>, <Avaritia:Resource:2>, <ExtraUtilities:block_bedrockium>],
  [<ExtraUtilities:block_bedrockium>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <Avaritia:Resource:2>, <ExtraUtilities:block_bedrockium>],
  [<ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>, <ExtraUtilities:block_bedrockium>]]);

mods.avaritia.ExtremeCrafting.addShaped (<HardcoreQuesting:hearts>,
[[null, null, <minecraft:bedrock>, <minecraft:bedrock>, null, <minecraft:bedrock>, <minecraft:bedrock>, null, null],
  [null, <minecraft:bedrock>, <TConstruct:heartCanister:1>, <TConstruct:heartCanister:1>, <minecraft:bedrock>, <TConstruct:heartCanister:1>, <TConstruct:heartCanister:1>, <minecraft:bedrock>, null],
  [<minecraft:bedrock>, <magicalcrops:WatershardEssence>, <ore:shardEarth>, <magicalcrops:EarthshardEssence>, <magicalcrops:EarthshardEssence>, <magicalcrops:EarthshardEssence>, <ore:shardEarth>, <magicalcrops:WatershardEssence>, <minecraft:bedrock>],
  [<minecraft:bedrock>, <magicalcrops:WatershardEssence>, <magicalcrops:WatershardEssence>, <ore:shardEarth>, <TConstruct:heartCanister:1>, <ore:shardEarth>, <magicalcrops:WatershardEssence>, <magicalcrops:WatershardEssence>, <minecraft:bedrock>],
  [<minecraft:bedrock>, <ore:shardWater>, <ore:shardWater>, <ore:shardWater>, <Avaritia:Resource:5>, <ore:shardWater>, <ore:shardWater>, <ore:shardWater>, <minecraft:bedrock>],
  [null, <minecraft:bedrock>, <magicalcrops:WatershardEssence>, <ore:shardEarth>, <magicalcrops:EarthshardEssence>, <ore:shardEarth>, <magicalcrops:WatershardEssence>, <minecraft:bedrock>, null],
  [null, null, <minecraft:bedrock>, <magicalcrops:EarthshardEssence>, <magicalcrops:EarthshardEssence>, <magicalcrops:EarthshardEssence>, <minecraft:bedrock>, null, null],
  [null, null, null, <minecraft:bedrock>, <magicalcrops:EarthshardEssence>, <minecraft:bedrock>, null, null, null],
  [null, null, null, null, <minecraft:bedrock>, null, null, null, null]]);



