// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED


// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

mods.avaritia.ExtremeCrafting.addShapeless (<Avaritia:Resource:5>, [<Avaritia:Ultimate_Stew>, <Avaritia:Cosmic_Meatballs>, <Avaritia:Endest_Pearl>, <minecraft:dragon_egg>, <avaritiaddons:CompressedChest>, <cardboardboxes:cbCardboardBox>, <adventurebackpack:adventureBackpack:57>, <AgriCraft:journal>, <appliedenergistics2:tile.BlockMolecularAssembler>,
<betterquesting:submit_station>, <ore:brDeviceCyaniteProcessor>, <minecraft:skull:3>, <Botania:phantomInk>, <BuildCraft|Robotics:zonePlan>, <chancecubes:Chance_Icosahedron>, <cookingbook:recipebook:1>, <EnderIO:blockTransceiver>, <EnderStorage:enderChest:*>,
<equivalentenergistics:EMCCrafter:3>, <equivalentenergistics:EMCCondenser:3>, <evilcraft:biomeExtract:1>, <exastris:doll_thaumic>, <exnihilo:doll_angry>, <ExtraUtilities:peaceful_table_top>, <ore:gemPurpleDiamond>, <ExtraTiC:battelSign:148>, <HardcoreQuesting:item_barrel>,
<IguanaTweaksTConstruct:skullItem:3>, <ore:itemSlag>, <ironbackpacks:nestingAdvancedUpgrade>, <IronChest:BlockIronChest:5>, <ironfurnaces:crystal_furnace>, <JABBA:upgradeCore:9>, <LogisticsPipes:item.PipeLogisticsChassiMk5>, <magicalcrops:essence_storage:5>, <magicalcrops:CropBooster>,
<MineFactoryReloaded:machine.2:10>, <ore:oreNetherTungsten>, <OpenBlocks:sky>, <OpenBlocks:canvas>, <ore:cropFleshroot>, <ore:materialPressedwax>, <ProjectE:interdiction_torch>, <peaether:alchemicalCoinItem>, <QuantumStorage:quantumdsu>,
<Railcraft:part.turbine.disk>, <SimpleLabels:label>, <StorageDrawers:halfCustom4>, <Thaumcraft:blockCosmeticSolid:5>, <aether:enchantedGravitite>, <ThermalExpansion:Workbench:4>, <ThermalDynamics:ThermalDynamics_0:6>, <ore:rodBlitz>, <TConstruct:materials:1>,
<TConstruct:materials:17>, <eternalsingularity:eternal_singularity>]);

mods.avaritia.ExtremeCrafting.addShapeless (<ExtraPlanets:tile.decorativeBlocks2:5>, [<Botania:pavement:5>, <ore:mysticFlowerGreenDouble>, <Botania:mushroom:13>, <Botania:petalBlock:13>, <Botania:shinyFlower:13>, <Botania:miniIsland:13>, <Botania:manaBeacon:13>, <Botania:unstableBlock:13>, <ore:mysticFlowerGreen>,
<AgriCraft:seedBotaniaGreen>, <minecraft:dye:2>, <minecraft:carpet:13>, <minecraft:stained_glass_pane:13>, <minecraft:stained_hardened_clay:13>, <minecraft:stained_glass:13>, <minecraft:wool:13>, <ExtraUtilities:color_brick:13>, <ExtraUtilities:color_redstoneLight:13>,
<ExtraUtilities:color_quartzBlock:13>, <ExtraUtilities:color_hellsand:13>, <ExtraUtilities:color_stone:13>, <ExtraUtilities:color_lightgem:13>, <ExtraUtilities:colorWoodPlanks:13>, <ExtraUtilities:colorStoneBrick:13>, <ExtraPlanets:tier11Items:9>, <ExtraPlanets:tile.kepler22bPlanks:4>, <ExtraPlanets:tier11Items:4>,
<ExtraPlanets:tile.kepler22bNewMapleLeaves2>, <ExtraPlanets:tile.kepler22bMapleSaplings:4>, <ExtraPlanets:tile.kepler22bMapleLogs2>, <Botania:dye:13>, <Botania:petal:13>, <Botania:pavement5Slab>, <Botania:pavement5Stairs>, <Railcraft:post.metal.platform:2>, <Railcraft:post.metal:2>,
<Thaumcraft:blockWoodenDevice:8>, <TConstruct:heartCanister:5>, <ore:dyeCeramicGreen>, <MineFactoryReloaded:stainedglass.pane:13>, <MineFactoryReloaded:stainedglass.block:13>, <MineFactoryReloaded:conveyor:13>, <ExtraPlanets:slimeBlock>, <minecraft:slime_ball>, <ExtraUtilities:greenscreen:13>,
<ExtraUtilities:greenscreen:5>, <ExtraUtilities:color_blockCoal:13>, <ExtraUtilities:color_blockRedstone:13>, <ExtraUtilities:color_obsidian:13>, <ExtraUtilities:color_blockLapis:13>, <ExtraUtilities:color_stonebrick:13>, <chisel:beacon:2>, <chisel:antiBlock:2>, <appliedenergistics2:item.ItemMultiPart:53>,
<appliedenergistics2:item.ItemMultiPart:13>, <appliedenergistics2:item.ItemMultiPart:73>, <appliedenergistics2:item.ItemMultiPart:33>, <aether:greenSkyrootSapling>, <aether:greenSkyrootLeaves:1>, <aether:aercloud:3>, <TConstruct:GlassPaneClearStained:13>, <TConstruct:heartCanister:6>, <ThermalExpansion:Rockwool:13>,
<Thaumcraft:blockCandle:13>, <TConstruct:GlassBlock.StainedClear:13>, <TConstruct:slime.gel:1>, <TConstruct:WoolSlab1:5>, <ore:blockEmerald>, <ore:gemEmerald>, <ore:cropEmeryllis>, <ore:oreEmerald>, <ore:chipsetEmerald>,
<BuildCraft|Transport:item.buildcraftPipe.pipeitemsemerald>, <BuildCraft|Transport:item.buildcraftPipe.pipefluidsemerald>, <BuildCraft|Transport:item.buildcraftPipe.pipepoweremerald>, <universalsingularities:universal.vanilla.singularity:1>, <MineFactoryReloaded:rubberwood.leaves>, <Thaumcraft:blockMagicalLeaves>, <ExtraPlanets:tile.ceres:8>, <ExtraPlanets:ingotUranium>, <universalsingularities:universal.general.singularity:14>]);

mods.avaritia.ExtremeCrafting.addShapeless (<ExtraPlanets:tile.decorativeBlocks2:4>, [<ExtraUtilities:color_redstoneLight:4>, <ExtraUtilities:color_brick:4>, <minecraft:carpet:4>, <minecraft:wool:4>, <minecraft:stained_glass:4>, <ore:stainedClayYellow>, <minecraft:stained_glass_pane:4>, <minecraft:dye:11>, <ore:seedBotaniaYellow>,
<ore:dyeCeramicYellow>, <MineFactoryReloaded:stainedglass.pane:4>, <MineFactoryReloaded:stainedglass.block:4>, <MineFactoryReloaded:conveyor:4>, <ExtraUtilities:greenscreen:4>, <ExtraUtilities:color_blockCoal:4>, <ExtraUtilities:color_blockRedstone:4>, <ExtraUtilities:color_obsidian:4>, <ExtraUtilities:color_blockLapis:4>,
<Botania:pavement:4>, <ore:flowerYellow>, <TConstruct:heartCanister:3>, <ExtraPlanets:tier11Items:8>, <ore:gemYellowDiamond>, <ExtraPlanets:tile.kepler22bPlanks:3>, <ExtraPlanets:tile.kepler22bNewMapleLeaves:3>, <ExtraPlanets:tile.kepler22bMapleLogs:3>, <appliedenergistics2:item.ItemMultiPart:64>,
<BuildCraft|Transport:item.buildcraftPipe.pipefluidsgold>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsgold>, <ore:chipsetGold>, <ore:thermalexpansion:machineGold>, <chisel:woolen_clay:4>, <chisel:beacon:11>, <chisel:antiBlock:11>, <appliedenergistics2:item.ItemMultiPart:44>, <appliedenergistics2:item.ItemMultiPart:4>,
<aether:aetherLog:2>, <aether:aercloud:2>, <ExtraUtilities:spike_base_gold>, <ExtraUtilities:decorativeBlock2:4>, <ore:orePoorGold>, <IronChest:BlockIronChest:1>, <OpenBlocks:goldenegg>, <BuildCraft|Transport:item.buildcraftPipe.pipepowergold>, <ore:blockYellorium>,
<evilcraft:goldenString>, <ironbackpacks:jeweledFeather>, <ironfurnaces:gold_furnace>, <Avaritia:Singularity:1>, <universalsingularities:universal.bigReactors.singularity:4>, <aether:goldenOakLeaves:1>, <ore:oreGold>, <minecraft:golden_carrot>, <minecraft:gold_block>,
<minecraft:golden_apple:1>, <minecraft:double_plant>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny:1>, <Botania:quartzTypeSunny:2>, <Botania:quartzStairsSunny>, <minecraft:glowstone>, <minecraft:hay_block>,
<ExtraUtilities:color_lightgem:4>, <thermsingul:ThermalSingularity:3>, <ore:blockLumium>, <magicalcrops:essence_storage:2>, <magicalcropsdeco:essence_brick:4>, <ThermalExpansion:material>, <ore:dustBlitz>, <ore:dustPyrotheum>,
<universalsingularities:universal.general.singularity:4>, <ore:blockElectrum>, <ImmersiveEngineering:storage:9>, <ore:oreNetherSulfur>, <ThermalExpansion:Light>, <ThermalExpansion:Plate:5>, <ExtraUtilities:decorativeBlock1:8>, <ExtraUtilities:decorativeBlock2:7>, <BuildCraft|Transport:pipeWire:3>,
<Botania:thatch>, <Botania:blazeBlock>]);

mods.avaritia.ExtremeCrafting.addShapeless (<ExtraPlanets:tile.decorativeBlocks2:3>, [<minecraft:wool:3>, <ThermalExpansion:Rockwool:3>, <chisel:woolen_clay:3>, <minecraft:carpet:3>, <minecraft:clay>, <minecraft:stained_glass:3>, <MineFactoryReloaded:stainedglass.block:3>, <ore:paneGlassLightBlue>, <minecraft:stained_hardened_clay:3>,
<ExtraUtilities:color_hellsand:3>, <ExtraUtilities:color_redstoneLight:3>, <ExtraUtilities:color_brick:3>, <ExtraUtilities:color_stonebrick:3>, <ExtraUtilities:color_blockCoal:3>, <ExtraUtilities:color_blockRedstone:3>, <ExtraUtilities:color_obsidian:3>, <ExtraUtilities:color_blockLapis:3>, <ExtraUtilities:colorStoneBrick:3>,
<ExtraUtilities:colorWoodPlanks:3>, <ExtraUtilities:color_lightgem:3>, <ExtraUtilities:color_stone:3>, <ExtraUtilities:color_quartzBlock:3>, <Botania:quartzTypeMana>, <Botania:flower:3>, <Botania:miniIsland:3>, <Botania:mushroom:3>, <Botania:shinyFlower:3>, 
<Botania:doubleFlower1:3>, <AgriCraft:seedBotaniaLightBlue>, <Botania:petalBlock:3>, <Botania:storage:3>, <Botania:unstableBlock:3>, <Botania:manaBeacon:3>, <ExtraPlanets:tier8Items:6>, <ore:blockCyanite>, <ironfurnaces:diamond_furnace>,
<ore:blockTin>, <IronChest:BlockIronChest:2>, <ExtraPlanets:diamondApple>, <ExtraPlanets:diamondApple:1>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsdiamond>, <BuildCraft|Transport:item.buildcraftPipe.pipefluidsdiamond>, <BuildCraft|Transport:item.buildcraftPipe.pipepowerdiamond>, <ExtraUtilities:spike_base_diamond>, <chisel:antiBlock:12>,
<ExtraUtilities:greenscreen:3>, <Avaritia:Crystal_Matrix>, <Botania:prismarine>, <Botania:prismarine:1>, <Botania:prismarine1Slab>, <BuildCraft|Silicon:redstoneChipset:3>, <MineFactoryReloaded:conveyor:3>, <aether:aercloud:1>, <aether:blueSkyrootLeaves:1>,
<TConstruct:slime.gel>, <TConstruct:CraftedSoil:5>, <TConstruct:explosive.slime:2>, <magicalcrops:CropBooster>, <EnderIO:itemMaterial:5>, <chisel:beacon:12>, <universalsingularities:universal.vanilla.singularity:2>, <thermsingul:ThermalSingularity>, <universalsingularities:universal.bigReactors.singularity:1>]);

mods.avaritia.ExtremeCrafting.addShapeless (<ExtraPlanets:tile.decorativeBlocks2:2>, [<minecraft:wool:11>, <minecraft:carpet:11>, <chisel:woolen_clay:11>, <minecraft:stained_glass:11>, <TConstruct:GlassBlock.StainedClear:11>, <MineFactoryReloaded:stainedglass.block:11>, <ore:stainedGlassPaneBlue>, <minecraft:stained_hardened_clay:11>, <Botania:prismarine:2>,
<ExtraUtilities:color_stonebrick:11>, <minecraft:lapis_ore>, <minecraft:lapis_block>, <ExtraUtilities:color_blockLapis:11>, <ExtraUtilities:color_obsidian:11>, <ExtraUtilities:color_redstoneLight:3>, <ExtraUtilities:color_hellsand:11>, <ExtraUtilities:color_brick:11>, <ExtraUtilities:color_blockCoal:11>,
<ExtraUtilities:color_blockRedstone:11>, <ExtraUtilities:color_lightgem:11>, <ExtraUtilities:color_stone:11>, <ExtraUtilities:colorStoneBrick:11>, <ExtraUtilities:trashcan:1>, <ExtraUtilities:generator.64:10>, <ExtraUtilities:colorWoodPlanks:11>, <ExtraPlanets:tile.kepler22bMapleLogs>, <ExtraPlanets:tile.kepler22bPlanks>, <ExtraPlanets:tier11Items:5>, <ExtraPlanets:tile.kepler22bMapleSaplings>, <ExtraPlanets:tile.kepler22bNewMapleLeaves>,
<aether:darkBlueSkyrootSapling>, <aether:darkBlueSkyrootLeaves:1>, <ore:oreBlueDiamond>, <ore:gemBlueDiamond>, <ore:oreLapis>, <ore:blockLapis>, <ore:oreDiamond>, <minecraft:diamond_block>, <TConstruct:decoration.multibrickmetal:6>,
<BigReactors:BRMetalBlock:3>, <ore:blockEnderium>, <ThermalExpansion:Strongbox:4>, <ThermalExpansion:Cache:4>, <ThermalExpansion:Workbench:1>, <Botania:pavement:2>, <Botania:storage>, <Botania:flower:11>, <Botania:shinyFlower:11>,
<Botania:doubleFlower2:3>, <Botania:mushroom:11>, <Botania:miniIsland:11>, <AgriCraft:seedBotaniaBlue>, <Botania:petalBlock:11>, <magicalcrops:essence_storage:3>, <magicalcropsdeco:essence_brick:11>, <ore:dyeCeramicBlue>, <BuildCraft|Builders:blueprintItem>,
<chisel:antiBlock:4>, <ExtraUtilities:greenscreen:11>, <chisel:beacon:4>, <Avaritia:Singularity:2>, <universalsingularities:universal.vanilla.singularity:2>, <universalsingularities:universal.bigReactors.singularity>, <thermsingul:ThermalSingularity:4>]);

mods.avaritia.ExtremeCrafting.addShapeless (<ExtraPlanets:tile.decorativeBlocks2>, [<minecraft:stained_glass>, <TConstruct:GlassBlock.StainedClear>, <MineFactoryReloaded:stainedglass.block>, <ore:paneGlassWhite>, <minecraft:wool>, <ThermalExpansion:Rockwool>, <chisel:woolen_clay>, <minecraft:stained_hardened_clay>, <ore:oreIron>,
<ore:ingotIron>, <ore:blockIron>, <ore:oreQuartz>, <ore:blockQuartz>, <ore:slabQuartz>, <minecraft:quartz_block:1>, <minecraft:quartz_block:2>, <minecraft:quartz_stairs>, <appliedenergistics2:tile.BlockQuartz>,
<appliedenergistics2:tile.BlockQuartzPillar>, <appliedenergistics2:tile.BlockQuartzChiseled>, <appliedenergistics2:tile.QuartzSlabBlock>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsquartz>, <BuildCraft|Transport:item.buildcraftPipe.pipefluidsquartz>, <BuildCraft|Transport:item.buildcraftPipe.pipepowerquartz>, <ore:dustNetherQuartz>, <appliedenergistics2:item.ItemMultiMaterial:11>, <ore:crystalChargedCertusQuartz>,
<minecraft:red_flower:6>, <minecraft:red_flower:8>, <ore:livingrock>, <Botania:unstableBlock>, <Botania:manaBeacon>, <AgriCraft:seedBotaniaWhite>, <Botania:petalBlock>, <Botania:shinyFlower>, <Botania:mushroom>,
<ore:mysticFlowerWhiteDouble>, <Botania:pavement>, <ExtraUtilities:color_brick>, <ExtraUtilities:color_stonebrick>, <ExtraUtilities:color_blockLapis>, <ExtraUtilities:color_obsidian>, <ExtraUtilities:color_blockRedstone>, <ExtraUtilities:color_blockCoal>, <ExtraUtilities:color_redstoneLight>,
<ore:glowstoneBlack>, <ExtraUtilities:colorWoodPlanks>, <ExtraUtilities:greenscreen>, <chisel:antiBlock:15>, <ore:blockUnstable>, <ExtraUtilities:color_quartzBlock>, <ExtraUtilities:sound_muffler>, <ExtraUtilities:sound_muffler:1>, <ExtraUtilities:generator.64:5>,
<MineFactoryReloaded:machineblock>, <OpenBlocks:elevator>, <OpenBlocks:canvas>, <Railcraft:cube:7>, <ExtraPlanets:tile.decorativeBlocks>, <ExtraPlanets:item.wafer:5>, <harvestcraft:spamcompressedsaltBlockalt>, <rftools:dimensionalBlankBlock>, <OpenBlocks:elevator>,
<ExtraPlanets:ironApple>, <ExtraPlanets:ironApple:1>, <aether:whiteApple>, <IronChest:BlockIronChest>, <ironfurnaces:iron_furnace>, <ExtraUtilities:spike_base>, <BuildCraft|Core:ironGearItem>, <MineFactoryReloaded:conveyor>, <MineFactoryReloaded:ceramicdye>,
<TConstruct:oreBerries:4>, <Thaumcraft:blockWoodenDevice:8>, <Thaumcraft:blockCandle>, <chisel:cloud>, <aether:aercloud>, <ExtraPlanets:tile.uranus:7>, <Avaritia:Singularity>, <Avaritia:Singularity:4>, <universalsingularities:universal.extraPlanets.singularity:5>]);

mods.avaritia.ExtremeCrafting.addShapeless (<ExtraPlanets:tile.decorativeBlocks2:1>, [<ore:stainedGlassPaneRed>, <ore:stainedClayRed>, <minecraft:redstone_block>, <minecraft:redstone_torch>, <ore:oreRedstone>, <minecraft:red_flower>, <minecraft:wool:14>, <minecraft:sand:1>, <Botania:unstableBlock:14>,
<Botania:manaBeacon:14>, <Botania:petalBlock:14>, <AgriCraft:seedBotaniaRed>, <Botania:flower:14>, <Botania:shinyFlower:14>, <ore:mysticFlowerRedDouble>, <Botania:mushroom:14>, <Botania:miniIsland:14>, <Botania:pavement:3>,
<minecraft:comparator>, <minecraft:repeater>, <ore:dustRedstone>, <BuildCraft|Silicon:redstoneChipset>, <ore:chipsetComp>, <BuildCraft|Silicon:redstoneCrystal>, <BuildCraft|Robotics:redstone_board>, <ore:dyeRed>, <Botania:quartzTypeRed>,
<evilcraft:undeadLog>, <evilcraft:undeadSapling>, <evilcraft:reinforcedUndeadPlank>, <evilcraft:bloodWaxedCoalBlock>, <evilcraft:darkPowerGemBlock>, <ExtraPlanets:tile.kepler22bMapleLogs:1>, <ExtraPlanets:tile.kepler22bMapleSaplings:1>, <ExtraPlanets:tile.kepler22bNewMapleLeaves:1>, <ExtraPlanets:tile.kepler22bPlanks:1>,
<ore:oreRedDiamond>, <ore:oreRedGem>, <ore:gemRedGem>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ExtraPlanets:tile.jupiter:11>, <EnderIO:blockIngotStorage:3>, <EnderIO:itemRedstoneConduit>, <Botania:pavement:3>,
<BuildCraft|Transport:pipeWire>, <ExtraUtilities:greenscreen:14>, <ExtraUtilities:color_obsidian:14>, <ExtraUtilities:color_quartzBlock:14>, <ExtraUtilities:color_lightgem:14>, <ExtraUtilities:generator.64:4>, <MineFactoryReloaded:conveyor:14>, <MineFactoryReloaded:stainedglass.block:14>, <MineFactoryReloaded:stainedglass.pane:14>,
<MineFactoryReloaded:ceramicdye:14>, <ProjectE:matter_block:1>, <ProjectE:rm_furnace>, <Thaumcraft:blockWoodenDevice:8>, <Thaumcraft:blockCandle:14>, <ThermalDynamics:relay>, <ThermalExpansion:Rockwool:14>, <ThermalExpansion:diagram:1>, <chisel:antiBlock:1>,
<chisel:beacon:1>, <minecraft:tnt>, <minecraft:netherrack>, <minecraft:brick_block>, <ore:cropShroomRed>, <magicalcropsdeco:essence_brick:14>, <Avaritia:Singularity:3>, <universalsingularities:universal.extraPlanets.singularity:4>, <universalsingularities:universal.enderIO.singularity:5>]);

mods.avaritia.ExtremeCrafting.addShapeless (<JABBA:upgradeCore:9>, [<JABBA:upgradeCore:8>, <JABBA:upgradeCore:8>, <JABBA:upgradeCore:8>]);
// ================================================================================
//#MARKER ADD SHAPED
mods.avaritia.ExtremeCrafting.addShaped (<TConstruct:heartCanister:5>,
[[null, null, <Avaritia:Resource:5>, <Avaritia:Resource:5>, null, <Avaritia:Resource:5>, <Avaritia:Resource:5>, null, null],
  [null, <Avaritia:Resource:5>, <ore:gemEmerald>, <ore:gemEmerald>, <Avaritia:Resource:5>, <ore:gemEmerald>, <ore:gemEmerald>, <Avaritia:Resource:5>, null],
  [<Avaritia:Resource:5>, <magicalcrops:CowEssence>, <ore:gemEmerald>, <ore:gemEmerald>, <magicalcrops:SheepEssence>, <ore:gemEmerald>, <ore:gemEmerald>, <magicalcrops:PigEssence>, <Avaritia:Resource:5>],
  [<Avaritia:Resource:5>, <magicalcrops:ChickenEssence>, <ore:gemEmerald>, <ProjectE:item.pe_life_stone>, <Botania:spawnerClaw>, <ProjectE:item.pe_life_stone>, <ore:gemEmerald>, <magicalcrops:GhastEssence>, <Avaritia:Resource:5>],
  [<Avaritia:Resource:5>, <magicalcrops:EndermanEssence>, <ore:gemEmerald>, <Botania:spawnerClaw>, <GalacticraftCore:item.key>, <Botania:spawnerClaw>, <ore:gemEmerald>, <magicalcrops:BlazeEssence>, <Avaritia:Resource:5>],
  [null, <Avaritia:Resource:5>, <magicalcrops:SlimeEssence>, <ProjectE:item.pe_life_stone>, <Botania:spawnerClaw>, <ProjectE:item.pe_life_stone>, <magicalcrops:WitherEssence>, <Avaritia:Resource:5>, null],
  [null, null, <Avaritia:Resource:5>, <magicalcrops:CreeperEssence>, <magicalcrops:SpiderEssence>, <magicalcrops:SkeletonEssence>, <Avaritia:Resource:5>, null, null],
  [null, null, null, <Avaritia:Resource:5>, <ore:gemEmerald>, <Avaritia:Resource:5>, null, null, null],
  [null, null, null, null, <Avaritia:Resource:5>, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<TConstruct:heartCanister:3>,
[[null, null, <Avaritia:Resource:5>, <Avaritia:Resource:5>, null, <Avaritia:Resource:5>, <Avaritia:Resource:5>, null, null],
  [null, <Avaritia:Resource:5>, <ore:ingotGold>, <ore:ingotGold>, <Avaritia:Resource:5>, <ore:ingotGold>, <ore:ingotGold>, <Avaritia:Resource:5>, null],
  [<Avaritia:Resource:5>, <magicalcrops:CowEssence>, <ore:ingotGold>, <ore:ingotGold>, <magicalcrops:SheepEssence>, <ore:ingotGold>, <ore:ingotGold>, <magicalcrops:PigEssence>, <Avaritia:Resource:5>],
  [<Avaritia:Resource:5>, <magicalcrops:ChickenEssence>, <ore:ingotGold>, <ProjectE:item.pe_life_stone>, <Botania:spawnerClaw>, <ProjectE:item.pe_life_stone>, <ore:ingotGold>, <magicalcrops:GhastEssence>, <Avaritia:Resource:5>],
  [<Avaritia:Resource:5>, <magicalcrops:EndermanEssence>, <ore:ingotGold>, <Botania:spawnerClaw>, <ExtraPlanets:tile.decorativeBlocks2:4>, <Botania:spawnerClaw>, <ore:ingotGold>, <magicalcrops:BlazeEssence>, <Avaritia:Resource:5>],
  [null, <Avaritia:Resource:5>, <magicalcrops:SlimeEssence>, <ProjectE:item.pe_life_stone>, <Botania:spawnerClaw>, <ProjectE:item.pe_life_stone>, <magicalcrops:WitherEssence>, <Avaritia:Resource:5>, null],
  [null, null, <Avaritia:Resource:5>, <magicalcrops:CreeperEssence>, <magicalcrops:SpiderEssence>, <magicalcrops:SkeletonEssence>, <Avaritia:Resource:5>, null, null],
  [null, null, null, <Avaritia:Resource:5>, <ore:ingotGold>, <Avaritia:Resource:5>, null, null, null],
  [null, null, null, null, <Avaritia:Resource:5>, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<TConstruct:heartCanister:1>,
[[null, null, <Avaritia:Resource:5>, <Avaritia:Resource:5>, null, <Avaritia:Resource:5>, <Avaritia:Resource:5>, null, null],
  [null, <Avaritia:Resource:5>, <ore:ingotRedstoneAlloy>, <ore:ingotRedstoneAlloy>, <Avaritia:Resource:5>, <ore:ingotRedstoneAlloy>, <ore:ingotRedstoneAlloy>, <Avaritia:Resource:5>, null],
  [<Avaritia:Resource:5>, <magicalcrops:CowEssence>, <ore:ingotRedstoneAlloy>, <ore:ingotRedstoneAlloy>, <magicalcrops:SheepEssence>, <ore:ingotRedstoneAlloy>, <ore:ingotRedstoneAlloy>, <magicalcrops:PigEssence>, <Avaritia:Resource:5>],
  [<Avaritia:Resource:5>, <magicalcrops:ChickenEssence>, <ore:ingotRedstoneAlloy>, <ProjectE:item.pe_life_stone>, <Botania:spawnerClaw>, <ProjectE:item.pe_life_stone>, <ore:ingotRedstoneAlloy>, <magicalcrops:GhastEssence>, <Avaritia:Resource:5>],
  [<Avaritia:Resource:5>, <magicalcrops:EndermanEssence>, <ore:ingotRedstoneAlloy>, <Botania:spawnerClaw>, <ExtraPlanets:tile.decorativeBlocks2:1>, <Botania:spawnerClaw>, <ore:ingotRedstoneAlloy>, <magicalcrops:BlazeEssence>, <Avaritia:Resource:5>],
  [null, <Avaritia:Resource:5>, <magicalcrops:SlimeEssence>, <ProjectE:item.pe_life_stone>, <Botania:spawnerClaw>, <ProjectE:item.pe_life_stone>, <magicalcrops:WitherEssence>, <Avaritia:Resource:5>, null],
  [null, null, <Avaritia:Resource:5>, <magicalcrops:CreeperEssence>, <magicalcrops:SpiderEssence>, <magicalcrops:SkeletonEssence>, <Avaritia:Resource:5>, null, null],
  [null, null, null, <Avaritia:Resource:5>, <ore:ingotRedstoneAlloy>, <Avaritia:Resource:5>, null, null, null],
  [null, null, null, null, <Avaritia:Resource:5>, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<OpenBlocks:goldenegg>,
[[null, null, null, <aether:goldenAmber>, <aether:goldenAmber>, <aether:goldenAmber>, null, null, null],
  [null, null, <aether:goldenAmber>, <OpenBlocks:goldenEye:*>, <OpenBlocks:goldenEye:*>, <OpenBlocks:goldenEye:*>, <aether:goldenAmber>, null, null],
  [null, <aether:goldenAmber>, <OpenBlocks:goldenEye:*>, <ExtraTiC:chunk:147>, <ExtraTiC:chunk:147>, <ExtraTiC:chunk:147>, <OpenBlocks:goldenEye:*>, <aether:goldenAmber>, null],
  [null, <aether:goldenAmber>, <OpenBlocks:goldenEye:*>, <ExtraTiC:chunk:147>, <MineFactoryReloaded:safarinet.jailer.fancy>, <ExtraTiC:chunk:147>, <OpenBlocks:goldenEye:*>, <aether:goldenAmber>, null],
  [<aether:goldenAmber>, <OpenBlocks:goldenEye:*>, <ExtraTiC:chunk:147>, <MineFactoryReloaded:safarinet.jailer.fancy>, <Avaritia:Singularity:1>, <MineFactoryReloaded:safarinet.jailer.fancy>, <ExtraTiC:chunk:147>, <OpenBlocks:goldenEye:*>, <aether:goldenAmber>],
  [<aether:goldenAmber>, <OpenBlocks:goldenEye:*>, <ExtraTiC:chunk:147>, <MineFactoryReloaded:bucket.sludge>, <MineFactoryReloaded:safarinet.jailer.fancy>, <MineFactoryReloaded:bucket.sludge>, <ExtraTiC:chunk:147>, <OpenBlocks:goldenEye:*>, <aether:goldenAmber>],
  [<aether:goldenAmber>, <OpenBlocks:goldenEye:*>, <ExtraTiC:chunk:147>, <ExtraTiC:chunk:147>, <ExtraTiC:chunk:147>, <ExtraTiC:chunk:147>, <ExtraTiC:chunk:147>, <OpenBlocks:goldenEye:*>, <aether:goldenAmber>],
  [null, <aether:goldenAmber>, <OpenBlocks:goldenEye:*>, <OpenBlocks:goldenEye:*>, <OpenBlocks:goldenEye:*>, <OpenBlocks:goldenEye:*>, <OpenBlocks:goldenEye:*>, <aether:goldenAmber>, null],
  [null, null, <aether:goldenAmber>, <aether:goldenAmber>, <aether:goldenAmber>, <aether:goldenAmber>, <aether:goldenAmber>, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<minecraft:dragon_egg>,
[[null, null, null, <ore:elvenDragonstone>, <ore:elvenDragonstone>, <ore:elvenDragonstone>, null, null, null],
  [null, null, <ore:elvenDragonstone>, <magicalcrops:EndermanEssence>, <magicalcrops:EndermanEssence>, <magicalcrops:EndermanEssence>, <ore:elvenDragonstone>, null, null],
  [null, <ore:elvenDragonstone>, <magicalcrops:EndermanEssence>, <magicalcrops:ChickenEssence>, <magicalcrops:ChickenEssence>, <magicalcrops:ChickenEssence>, <magicalcrops:EndermanEssence>, <ore:elvenDragonstone>, null],
  [null, <ore:elvenDragonstone>, <magicalcrops:EndermanEssence>, <magicalcrops:ChickenEssence>, <OpenBlocks:filledbucket>, <magicalcrops:ChickenEssence>, <magicalcrops:EndermanEssence>, <ore:elvenDragonstone>, null],
  [<ore:elvenDragonstone>, <magicalcrops:EndermanEssence>, <magicalcrops:ChickenEssence>, <OpenBlocks:filledbucket>, <OpenBlocks:goldenegg>, <OpenBlocks:filledbucket>, <magicalcrops:ChickenEssence>, <magicalcrops:EndermanEssence>, <ore:elvenDragonstone>],
  [<ore:elvenDragonstone>, <magicalcrops:EndermanEssence>, <magicalcrops:ChickenEssence>, <OpenBlocks:filledbucket>, <OpenBlocks:filledbucket>, <OpenBlocks:filledbucket>, <magicalcrops:ChickenEssence>, <magicalcrops:EndermanEssence>, <ore:elvenDragonstone>],
  [<ore:elvenDragonstone>, <magicalcrops:EndermanEssence>, <magicalcrops:ChickenEssence>, <magicalcrops:ChickenEssence>, <magicalcrops:ChickenEssence>, <magicalcrops:ChickenEssence>, <magicalcrops:ChickenEssence>, <magicalcrops:EndermanEssence>, <ore:elvenDragonstone>],
  [null, <ore:elvenDragonstone>, <magicalcrops:EndermanEssence>, <magicalcrops:EndermanEssence>, <magicalcrops:EndermanEssence>, <magicalcrops:EndermanEssence>, <magicalcrops:EndermanEssence>, <ore:elvenDragonstone>, null],
  [null, null, <ore:elvenDragonstone>, <ore:elvenDragonstone>, <ore:elvenDragonstone>, <ore:elvenDragonstone>, <ore:elvenDragonstone>, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<IronChest:ironGoldUpgrade>,
[[<ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, null, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, null, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, <ore:runeGreedB>, <IronChest:BlockIronChest>, <ore:runeGreedB>, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, null, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, null, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>]]);

mods.avaritia.ExtremeCrafting.addShaped (<IronChest:goldDiamondUpgrade>,
[[<ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>],
  [<ore:blockDiamond>, null, null, null, null, null, null, null, <ore:blockDiamond>],
  [<ore:blockDiamond>, null, null, null, null, null, null, null, <ore:blockDiamond>],
  [<ore:blockDiamond>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockDiamond>],
  [<ore:blockDiamond>, null, null, <ore:runeGreedB>, <IronChest:BlockIronChest:1>, <ore:runeGreedB>, null, null, <ore:blockDiamond>],
  [<ore:blockDiamond>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockDiamond>],
  [<ore:blockDiamond>, null, null, null, null, null, null, null, <ore:blockDiamond>],
  [<ore:blockDiamond>, null, null, null, null, null, null, null, <ore:blockDiamond>],
  [<ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>]]);

mods.avaritia.ExtremeCrafting.addShaped (<IronChest:copperSilverUpgrade>,
[[<ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>],
  [<ore:blockSilver>, null, null, null, null, null, null, null, <ore:blockSilver>],
  [<ore:blockSilver>, null, null, null, null, null, null, null, <ore:blockSilver>],
  [<ore:blockSilver>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockSilver>],
  [<ore:blockSilver>, null, null, <ore:runeGreedB>, <IronChest:BlockIronChest:3>, <ore:runeGreedB>, null, null, <ore:blockSilver>],
  [<ore:blockSilver>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockSilver>],
  [<ore:blockSilver>, null, null, null, null, null, null, null, <ore:blockSilver>],
  [<ore:blockSilver>, null, null, null, null, null, null, null, <ore:blockSilver>],
  [<ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>, <ore:blockSilver>]]);

mods.avaritia.ExtremeCrafting.addShaped (<IronChest:silverGoldUpgrade>,
[[<ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, null, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, null, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, <ore:runeGreedB>, <IronChest:BlockIronChest:4>, <ore:runeGreedB>, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, null, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, null, null, null, null, null, null, null, <ore:blockGold>],
  [<ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>, <ore:blockGold>]]);

mods.avaritia.ExtremeCrafting.addShaped (<IronChest:copperIronUpgrade>,
[[<ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, null, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, null, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, <ore:runeGreedB>, <IronChest:BlockIronChest:3>, <ore:runeGreedB>, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, null, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, null, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>]]);

mods.avaritia.ExtremeCrafting.addShaped (<IronChest:diamondCrystalUpgrade>,
[[<ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>],
  [<ExtraUtilities:decorativeBlock2:5>, null, null, null, null, null, null, null, <ExtraUtilities:decorativeBlock2:5>],
  [<ExtraUtilities:decorativeBlock2:5>, null, null, null, null, null, null, null, <ExtraUtilities:decorativeBlock2:5>],
  [<ExtraUtilities:decorativeBlock2:5>, null, null, null, <ore:runeGreedB>, null, null, null, <ExtraUtilities:decorativeBlock2:5>],
  [<ExtraUtilities:decorativeBlock2:5>, null, null, <ore:runeGreedB>, <IronChest:BlockIronChest:2>, <ore:runeGreedB>, null, null, <ExtraUtilities:decorativeBlock2:5>],
  [<ExtraUtilities:decorativeBlock2:5>, null, null, null, <ore:runeGreedB>, null, null, null, <ExtraUtilities:decorativeBlock2:5>],
  [<ExtraUtilities:decorativeBlock2:5>, null, null, null, null, null, null, null, <ExtraUtilities:decorativeBlock2:5>],
  [<ExtraUtilities:decorativeBlock2:5>, null, null, null, null, null, null, null, <ExtraUtilities:decorativeBlock2:5>],
  [<ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>, <ExtraUtilities:decorativeBlock2:5>]]);

mods.avaritia.ExtremeCrafting.addShaped (<IronChest:diamondObsidianUpgrade>,
[[<Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, null, null, null, null, null, null, null, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, null, null, null, null, null, null, null, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, null, null, null, <ore:runeGreedB>, null, null, null, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, null, null, <ore:runeGreedB>, <IronChest:BlockIronChest:2>, <ore:runeGreedB>, null, null, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, null, null, null, <ore:runeGreedB>, null, null, null, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, null, null, null, null, null, null, null, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, null, null, null, null, null, null, null, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>]]);
  
mods.avaritia.ExtremeCrafting.addShaped (<IronChest:woodCopperUpgrade>,
[[<ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>],
  [<ore:blockCopper>, null, null, null, null, null, null, null, <ore:blockCopper>],
  [<ore:blockCopper>, null, null, null, null, null, null, null, <ore:blockCopper>],
  [<ore:blockCopper>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockCopper>],
  [<ore:blockCopper>, null, null, <ore:runeGreedB>, <ore:chestWood>, <ore:runeGreedB>, null, null, <ore:blockCopper>],
  [<ore:blockCopper>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockCopper>],
  [<ore:blockCopper>, null, null, null, null, null, null, null, <ore:blockCopper>],
  [<ore:blockCopper>, null, null, null, null, null, null, null, <ore:blockCopper>],
  [<ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>]]);

mods.avaritia.ExtremeCrafting.addShaped (<IronChest:woodIronUpgrade>,
[[<ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, null, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, null, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, <ore:runeGreedB>, <ore:chestWood>, <ore:runeGreedB>, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, <ore:runeGreedB>, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, null, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, null, null, null, null, null, null, null, <ore:blockIron>],
  [<ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>]]);

mods.avaritia.ExtremeCrafting.addShaped (<ExtraUtilities:peaceful_table_top>,
[[null, <Avaritia:Resource>, <Avaritia:Resource>, <Avaritia:Resource>, <Avaritia:Resource>, <Avaritia:Resource>, <Avaritia:Resource>, <Avaritia:Resource>, null],
  [null, <chisel:woolen_clay:13>, <chisel:woolen_clay:13>, <chisel:woolen_clay:13>, <Botania:forestEye>, <chisel:woolen_clay:13>, <chisel:woolen_clay:13>, <chisel:woolen_clay:13>, null],
  [null, <Botania:livingwood:1>, <Botania:livingwood:1>, <Botania:livingwood:1>, <Botania:livingwood:1>, <Botania:livingwood:1>, <Botania:livingwood:1>, <Botania:livingwood:1>, null],
  [null, <Botania:livingwood:1>, <magicalcrops:SkeletonEssence>, <magicalcrops:SkeletonEssence>, <EnderIO:blockPoweredSpawner>, <magicalcrops:SkeletonEssence>, <magicalcrops:SkeletonEssence>, <Botania:livingwood:1>, null],
  [null, <Botania:livingwood:1>, <magicalcrops:SpiderEssence>, <magicalcrops:SpiderEssence>, <EnderIO:blockPoweredSpawner>, <magicalcrops:SpiderEssence>, <magicalcrops:SpiderEssence>, <Botania:livingwood:1>, null],
  [null, <Botania:livingwood:1>, <magicalcrops:CreeperEssence>, <magicalcrops:CreeperEssence>, <EnderIO:blockPoweredSpawner>, <magicalcrops:CreeperEssence>, <magicalcrops:CreeperEssence>, <Botania:livingwood:1>, null],
  [null, <Botania:livingwood:1>, <magicalcrops:EndermanEssence>, <magicalcrops:EndermanEssence>, <EnderIO:blockPoweredSpawner>, <magicalcrops:EndermanEssence>, <magicalcrops:EndermanEssence>, <Botania:livingwood:1>, null],
  [null, <Botania:livingwood:1>, <magicalcrops:BlazeEssence>, <magicalcrops:BlazeEssence>, <EnderIO:blockPoweredSpawner>, <magicalcrops:BlazeEssence>, <magicalcrops:BlazeEssence>, <Botania:livingwood:1>, null],
  [null, <Botania:livingwood:1>, <ExtraUtilities:cursedearthside>, <ExtraUtilities:cursedearthside>, <ExtraUtilities:cursedearthside>, <ExtraUtilities:cursedearthside>, <ExtraUtilities:cursedearthside>, <Botania:livingwood:1>, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:condenser_mk1>,
[[null, null, null, <ProjectE:item.pe_covalence_dust>, <ProjectE:item.pe_covalence_dust:1>, <ProjectE:item.pe_covalence_dust:2>, null, null, null],
  [null, <Railcraft:machine.beta:11>, <Railcraft:machine.beta:11>, <Railcraft:machine.beta:11>, <Railcraft:machine.beta:11>, <Railcraft:machine.beta:11>, <Railcraft:machine.beta:11>, <Railcraft:machine.beta:11>, null],
  [null, <Railcraft:machine.beta:11>, <ore:blockUranium>, <ore:blockMithril>, <JABBA:upgradeStructural:6>, <ore:blockBlutonium>, <Botania:storage:1>, <Railcraft:machine.beta:11>, null],
  [<ProjectE:item.pe_covalence_dust>, <Railcraft:machine.beta:11>, <ore:blockMithril>, <ore:blockMithril>, <ProjectE:matter_block>, <ore:blockBlutonium>, <ore:blockBlutonium>, <Railcraft:machine.beta:11>, <ProjectE:item.pe_covalence_dust>],
  [<ProjectE:item.pe_covalence_dust:1>, <Railcraft:machine.beta:11>, <ore:blockUranium>, <ProjectE:matter_block>, <ProjectE:alchemical_chest>, <ProjectE:matter_block>, <Botania:storage:1>, <Railcraft:machine.beta:11>, <ProjectE:item.pe_covalence_dust:1>],
  [<ProjectE:item.pe_covalence_dust:2>, <Railcraft:machine.beta:11>, <ore:blockCyanite>, <ore:blockCyanite>, <ProjectE:matter_block>, <magicalcrops:essence_storage:3>, <magicalcrops:essence_storage:3>, <Railcraft:machine.beta:11>, <ProjectE:item.pe_covalence_dust:2>],
  [null, <Railcraft:machine.beta:11>, <ore:blockUranium>, <ore:blockCyanite>, <JABBA:upgradeStructural:6>, <magicalcrops:essence_storage:3>, <Botania:storage:1>, <Railcraft:machine.beta:11>, null],
  [null, <Railcraft:machine.beta:11>, <appliedenergistics2:item.ItemSpatialStorageCell.128Cubed>, <Railcraft:machine.beta:11>, <TConstruct:decoration.multibrick>, <Railcraft:machine.beta:11>, <Railcraft:machine.epsilon>, <Railcraft:machine.beta:11>, null],
  [null, null, null, <ProjectE:item.pe_covalence_dust>, <ProjectE:item.pe_covalence_dust:1>, <ProjectE:item.pe_covalence_dust:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_destruction_catalyst>,
[[null, null, null, <evilcraft:garmonbozia>, <ore:crystalCinnabar>, <evilcraft:garmonbozia>, null, null, null],
  [null, null, <evilcraft:garmonbozia>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <evilcraft:garmonbozia>, null, null],
  [null, <evilcraft:garmonbozia>, <ore:crystalCinnabar>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter:1>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <evilcraft:garmonbozia>, null],
  [<evilcraft:garmonbozia>, <ore:crystalCinnabar>, <ProjectE:item.pe_matter:1>, <ProjectE:nova_cataclysm>, <OpenBlocks:devnull>, <ProjectE:item.pe_matter:1>, <ore:crystalCinnabar>, <evilcraft:garmonbozia>, null],
  [<evilcraft:garmonbozia>, <ore:crystalCinnabar>, <ProjectE:item.pe_matter:1>, <OpenBlocks:devnull>, <ore:blockUnstable>, <ProjectE:item.pe_matter:1>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <evilcraft:garmonbozia>],
  [<evilcraft:garmonbozia>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter:1>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <evilcraft:garmonbozia>],
  [<evilcraft:garmonbozia>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <evilcraft:garmonbozia>, null],
  [null, <evilcraft:garmonbozia>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <ore:crystalCinnabar>, <evilcraft:garmonbozia>, null, null],
  [null, null, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:nova_cataclysm>,
 [[null, null, null, null, null, null, null, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ExtraPlanets:fireBomb>, null, <ProjectE:nova_catalyst>, null, <ExtraPlanets:fireBomb>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, null, <ProjectE:nova_catalyst>, <ProjectE:nova_catalyst>, <ProjectE:nova_catalyst>, null, <ProjectE:item.pe_fuel:2>, null],
  [null, <ProjectE:item.pe_fuel:2>, <ProjectE:nova_catalyst>, <ProjectE:nova_catalyst>, <ore:ingotUnstable>, <ProjectE:nova_catalyst>, <ProjectE:nova_catalyst>, <ProjectE:item.pe_fuel:2>, null],
  [null, <ProjectE:item.pe_fuel:2>, null, <ProjectE:nova_catalyst>, <ProjectE:nova_catalyst>, <ProjectE:nova_catalyst>, null, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ExtraPlanets:fireBomb>, null, <ProjectE:nova_catalyst>, null, <ExtraPlanets:fireBomb>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:nova_catalyst>,
 [[null, null, null, null, null, null, null, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:1>, <ProjectE:item.pe_fuel:1>, <ProjectE:item.pe_fuel:1>, null, null, null],
  [null, null, <ExtraPlanets:nuclearBomb>, null, <minecraft:tnt>, null, <ExtraPlanets:nuclearBomb>, null, null],
  [null, <ProjectE:item.pe_fuel:1>, null, <minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>, null, <ProjectE:item.pe_fuel:1>, null],
  [null, <ProjectE:item.pe_fuel:1>, <minecraft:tnt>, <minecraft:tnt>, <ore:nuggetUnstable>, <minecraft:tnt>, <minecraft:tnt>, <ProjectE:item.pe_fuel:1>, null],
  [null, <ProjectE:item.pe_fuel:1>, null, <minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>, null, <ProjectE:item.pe_fuel:1>, null],
  [null, null, <ExtraPlanets:nuclearBomb>, null, <minecraft:tnt>, null, <ExtraPlanets:nuclearBomb>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:1>, <ProjectE:item.pe_fuel:1>, <ProjectE:item.pe_fuel:1>, null, null, null],
  [null, null, null, null, null, null, null, null, null]]);
  
mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_alchemical_bag>,
[[<Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <chisel:woolen_clay>, null, null, null, <chisel:woolen_clay>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>],
  [<ProjectE:item.pe_covalence_dust:2>, <chisel:woolen_clay>, <Botania:petalBlock>, <simplyjetpacks:components>, <simplyjetpacks:components>, <simplyjetpacks:components>, <Botania:petalBlock>, <chisel:woolen_clay>, <ProjectE:item.pe_covalence_dust:2>],
  [<chisel:woolen_clay>, <Botania:petalBlock>, <ore:materialHardenedleather>, <ProjectE:item.pe_klein_star>, null, <ProjectE:item.pe_klein_star:1>, null, <Botania:petalBlock>, <chisel:woolen_clay>],
  [<chisel:woolen_clay>, <Botania:petalBlock>, <Botania:petalBlock>, <ore:materialHardenedleather>, <EnderStorage:enderPouch>, null, <Botania:petalBlock>, <Botania:petalBlock>, <chisel:woolen_clay>],
  [<Thaumcraft:blockCosmeticSolid:1>, <chisel:woolen_clay>, <Botania:petalBlock>, <ProjectE:item.pe_klein_star:1>, <ProjectE:alchemical_chest>, <ProjectE:item.pe_klein_star>, <Botania:petalBlock>, <chisel:woolen_clay>, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, <chisel:woolen_clay>, <Botania:petalBlock>, null, <adventurebackpack:adventureBackpack>, <ore:materialHardenedleather>, <Botania:petalBlock>, <chisel:woolen_clay>, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, <chisel:woolen_clay>, <Botania:petalBlock>, <ProjectE:item.pe_klein_star>, null, <ProjectE:item.pe_klein_star:1>, <ore:materialHardenedleather>, <chisel:woolen_clay>, <Thaumcraft:blockCosmeticSolid:1>],
  [<Thaumcraft:blockCosmeticSolid:1>, <ProjectE:item.pe_covalence_dust:2>, <chisel:woolen_clay>, <Botania:petalBlock>, <Botania:petalBlock>, <Botania:petalBlock>, <chisel:woolen_clay>, <ProjectE:item.pe_covalence_dust:2>, <Thaumcraft:blockCosmeticSolid:1>],
  [null, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <chisel:woolen_clay>, <chisel:woolen_clay>, <chisel:woolen_clay>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<adventurebackpack:adventureBackpack>,
[[null, <enderioaddons:blockVoidTank>, <ironbackpacks:treatedLeather>, <magicalcrops:GoldEssence>, <magicalcrops:GoldEssence>, <magicalcrops:GoldEssence>, <ironbackpacks:treatedLeather>, <adventurebackpack:backpackComponent:2>, null],
  [null, <adventurebackpack:backpackComponent:2>, <ironbackpacks:treatedLeather>, <IronChest:BlockIronChest:1>, <IronChest:BlockIronChest:1>, <IronChest:BlockIronChest:1>, <ThermalExpansion:Machine:4>, <enderioaddons:blockVoidTank>, null],
  [null, <enderioaddons:blockVoidTank>, <ironbackpacks:treatedLeather>, <IronChest:BlockIronChest:1>, <MineFactoryReloaded:machine.1:3>, <IronChest:BlockIronChest:1>, <ThermalExpansion:Machine:5>, <adventurebackpack:backpackComponent:2>, null],
  [null, <adventurebackpack:backpackComponent:2>, <ironbackpacks:treatedLeather>, <IronChest:BlockIronChest:1>, <IronChest:BlockIronChest:1>, <IronChest:BlockIronChest:1>, <ironbackpacks:treatedLeather>, <enderioaddons:blockVoidTank>, null],
  [null, <enderioaddons:blockVoidTank>, <ironbackpacks:treatedLeather>, <ironbackpacks:treatedLeather>, <ironbackpacks:treatedLeather>, <ironbackpacks:treatedLeather>, <ironbackpacks:treatedLeather>, <adventurebackpack:backpackComponent:2>, null],
  [null, <adventurebackpack:backpackComponent:2>, <ore:materialHardenedleather>, <ore:materialHardenedleather>, <ironbackpacks:goldBackpack>, <ore:materialHardenedleather>, <TConstruct:CraftingSlab>, <enderioaddons:blockVoidTank>, null],
  [null, <enderioaddons:blockVoidTank>, <ore:materialHardenedleather>, <OpenBlocks:sleepingBag>, <ore:materialHardenedleather>, <adventurebackpack:backpackComponent:1>, <ore:materialHardenedleather>, <adventurebackpack:backpackComponent:2>, null],
  [null, <adventurebackpack:backpackComponent:2>, <ore:materialHardenedleather>, <aether:skyrootBedItem>, <harvestthenether:netherbedItem>, <minecraft:bed>, <ore:materialHardenedleather>, <enderioaddons:blockVoidTank>, null],
  [null, <enderioaddons:blockVoidTank>, <ore:materialHardenedleather>, <ore:materialHardenedleather>, <ore:materialHardenedleather>, <ore:materialHardenedleather>, <ore:materialHardenedleather>, <adventurebackpack:backpackComponent:2>, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_volcanite_amulet>,
[[null, null, null, null, null, <ImmersiveEngineering:storage:10>, <ImmersiveEngineering:storage:10>, <ImmersiveEngineering:storage:10>, null],
  [null, <ore:blockDarkSteel>, <ore:blockDarkSteel>, <ore:blockDarkSteel>, <Railcraft:machine.gamma:4>, <LogisticsPipes:item.PipeItemsFluidSupplier>, <ProjectE:item.pe_matter:1>, <Botania:redStringDispenser>, <MineFactoryReloaded:rocketlauncher>],
  [null, <ore:blockDarkSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <GalacticraftMars:item.null:6>, <magicalcrops:WitherProofGlass>, <ImmersiveEngineering:storage:10>, <ImmersiveEngineering:storage:10>],
  [<ore:stickSteel>, <ore:blockDarkSteel>, <ore:ingotElectricalSteel>, <magicalcrops:FireEssence>, <Thaumcraft:blockCrystal:1>, <magicalcrops:FireEssence>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, null],
  [<ore:stickSteel>, <ore:blockDarkSteel>, <Railcraft:machine.beta:6>, <Thaumcraft:blockCrystal:1>, <minecraft:lava_bucket>, <Thaumcraft:blockCrystal:1>, <ImmersiveEngineering:metalDevice:12>, <ore:ingotElectricalSteel>, null],
  [<ore:stickSteel>, <GalacticraftCore:item.canister>, <MineFactoryReloaded:machine.1:2>, <magicalcrops:FireEssence>, <Thaumcraft:blockCrystal:1>, <magicalcrops:FireEssence>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, null],
  [<ore:stickSteel>, <ore:ingotElectricalSteel>, <magicalcrops:WitherProofGlass>, <LogisticsPipes:item.itemUpgrade:22>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ProjectE:item.pe_gem_density>, <ore:ingotElectricalSteel>, null],
  [<ore:stickSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:blockDarkSteel>, <ore:blockDarkSteel>, null],
  [<Avaritia:Singularity>, <ore:stickSteel>, <ore:stickSteel>, <ore:stickSteel>, <ore:stickSteel>, <ore:stickSteel>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_evertide_amulet>,
[[null, null, null, null, null, <ImmersiveEngineering:storage:10>, <ImmersiveEngineering:storage:10>, <ImmersiveEngineering:storage:10>, null],
  [null, <ore:blockDarkSteel>, <ore:blockDarkSteel>, <ore:blockDarkSteel>, <Railcraft:machine.gamma:4>, <LogisticsPipes:item.PipeItemsFluidSupplier>, <ProjectE:item.pe_matter>, <Botania:redStringDispenser>, <MineFactoryReloaded:rocketlauncher>],
  [null, <ore:blockDarkSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <GalacticraftMars:item.null:6>, <ImmersiveEngineering:stoneDevice:4>, <ImmersiveEngineering:storage:10>, <ImmersiveEngineering:storage:10>],
  [<ore:stickSteel>, <ore:blockDarkSteel>, <ore:ingotElectricalSteel>, <magicalcrops:WaterEssence>, <Thaumcraft:blockCrystal:2>, <magicalcrops:WaterEssence>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, null],
  [<ore:stickSteel>, <ore:blockDarkSteel>, <Railcraft:machine.beta:6>, <Thaumcraft:blockCrystal:2>, <minecraft:water_bucket>, <Thaumcraft:blockCrystal:2>, <simplyjetpacks:components:63>, <ore:ingotElectricalSteel>, null],
  [<ore:stickSteel>, <GalacticraftCore:item.canister>, <MineFactoryReloaded:machine.1:2>, <magicalcrops:WaterEssence>, <Thaumcraft:blockCrystal:2>, <magicalcrops:WaterEssence>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, null],
  [<ore:stickSteel>, <ore:ingotElectricalSteel>, <ImmersiveEngineering:stoneDevice:4>, <LogisticsPipes:item.itemUpgrade:22>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ProjectE:item.pe_gem_density>, <ore:ingotElectricalSteel>, null],
  [<ore:stickSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:blockDarkSteel>, <ore:blockDarkSteel>, null],
  [<Avaritia:Singularity>, <ore:stickSteel>, <ore:stickSteel>, <ore:stickSteel>, <ore:stickSteel>, <ore:stickSteel>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_gem_density>,
[[null, null, null, null, <ExtraPlanets:item.wafer:5>, <ExtraPlanets:item.wafer:5>, <ExtraPlanets:item.wafer:5>, <ExtraPlanets:item.wafer:5>, <Thaumcraft:ItemEldritchObject>],
  [null, null, null, <ExtraPlanets:item.wafer:5>, <ExtraPlanets:item.wafer:5>, <TConstruct:heavyPlate:2>, <TConstruct:heavyPlate:2>, <TConstruct:heavyPlate:2>, <ExtraPlanets:item.wafer:5>],
  [null, null, <Thaumcraft:blockCosmeticSolid:1>, <ExtraPlanets:item.wafer:5>, <ProjectE:item.pe_fuel>, <ore:blockGold>, <ProjectE:item.pe_fuel>, <TConstruct:heavyPlate:2>, <ExtraPlanets:item.wafer:5>],
  [null, <Thaumcraft:blockCosmeticSolid:1>, <TConstruct:heavyPlate:500>, <ExtraPlanets:item.wafer:5>, <ProjectE:matter_block:1>, <minecraft:diamond_block>, <ProjectE:matter_block>, <TConstruct:heavyPlate:2>, <ExtraPlanets:item.wafer:5>],
  [<Thaumcraft:blockCosmeticSolid:1>, <ProjectE:matter_block>, <ore:gemWhiteGem>, <ExtraPlanets:item.wafer:5>, <ProjectE:item.pe_fuel>, <ore:blockIron>, <ProjectE:item.pe_fuel>, <TConstruct:heavyPlate:2>, <ExtraPlanets:item.wafer:5>],
  [<ore:ingotCrystalMatrix>, <ore:gemDark>, <ore:gemDark>, <ProjectE:fuel_block:2>, <ExtraPlanets:item.wafer:5>, <ExtraPlanets:item.wafer:5>, <ExtraPlanets:item.wafer:5>, <ExtraPlanets:item.wafer:5>, <ExtraPlanets:item.wafer:5>],
  [<TConstruct:materials:18>, <ore:gemDark>, <evilcraft:darkBlock>, <ore:gemDark>, <ore:gemWhiteGem>, <TConstruct:heavyPlate:500>, <Thaumcraft:blockCosmeticSolid:1>, null, null],
  [<ExtraUtilities:bedrockiumIngot>, <ore:gemDark>, <ore:gemDark>, <ore:gemDark>, <ProjectE:matter_block>, <Thaumcraft:blockCosmeticSolid:1>, null, null, null],
  [<TConstruct:arrowhead:31>, <ExtraUtilities:bedrockiumIngot>, <TConstruct:materials:18>, <ore:ingotCrystalMatrix>, <Thaumcraft:blockCosmeticSolid:1>, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_zero_ring>,
[[null, null, null, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:plateIron>,  null, null],
  [null, null, <Thaumcraft:FocusFrost>, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>, null],
  [null, <Botania:icePendant>, null, null, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <ProjectE:item.pe_ring_iron_band>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:plateIron>, <ore:compressedMeteoricIron>, null, null, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>],
  [null, <ore:plateIron>, <ore:compressedMeteoricIron>, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>, null],
  [null, null, <ore:plateIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:plateIron>, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_ignition>,
[[null, null, null, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:plateIron>,  null, null],
  [null, null, <Thaumcraft:FocusFire>, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>, null],
  [null, <ExtraPlanets:item.wafer:3>, null, null, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <ProjectE:item.pe_ring_iron_band>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:plateIron>, <ore:compressedMeteoricIron>, null, null, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>],
  [null, <ore:plateIron>, <ore:compressedMeteoricIron>, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>, null],
  [null, null, <ore:plateIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:plateIron>, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_harvest_god>,
[[null, null, null, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:plateIron>,  null, null],
  [null, null, <Thaumcraft:ItemGolemCore:3>, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>, null],
  [null, <Botania:auraRingGreater>, null, null, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <ProjectE:item.pe_ring_iron_band>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:plateIron>, <ore:compressedMeteoricIron>, null, null, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>],
  [null, <ore:plateIron>, <ore:compressedMeteoricIron>, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>, null],
  [null, null, <ore:plateIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:plateIron>, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_archangel_smite>,
[[null, null, null, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:plateIron>,  null, null],
  [null, null, <ProjectE:matter_block>, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>, null],
  [null, <ore:itemNetherStar>, null, null, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <ProjectE:item.pe_ring_iron_band>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:plateIron>, <ore:compressedMeteoricIron>, null, null, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>],
  [null, <ore:plateIron>, <ore:compressedMeteoricIron>, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>, null],
  [null, null, <ore:plateIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:plateIron>, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_black_hole>,
[[null, null, null, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:plateIron>,  null, null],
  [null, null, <ore:blockCosmicNeutronium>, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>, null],
  [null, <Botania:blackHoleTalisman>, null, null, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <ProjectE:item.pe_ring_iron_band>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:compressedMeteoricIron>, null, null, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, <simplyjetpacks:armorPlatings:1>, null, null, <ore:compressedMeteoricIron>],
  [<ore:plateIron>, <ore:compressedMeteoricIron>, null, null, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>],
  [null, <ore:plateIron>, <ore:compressedMeteoricIron>, null, null, null, <ore:compressedMeteoricIron>, <ore:plateIron>, null],
  [null, null, <ore:plateIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:compressedMeteoricIron>, <ore:plateIron>, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_repair_talisman>,
[[null, null, null, null, null, null, <ProjectE:item.pe_covalence_dust:1>, <ProjectE:item.pe_covalence_dust:1>, <Thaumcraft:blockMetalDevice:3>],
  [null, null, null, null, null, <ProjectE:item.pe_covalence_dust:1>, <Botania:storage:3>, <Botania:storage:3>, <ProjectE:item.pe_covalence_dust:1>],
  [null, null, null, null, <ProjectE:item.pe_covalence_dust:2>, <ProjectE:item.pe_covalence_dust:1>, <Botania:storage:3>, <Botania:storage:3>, <ProjectE:item.pe_covalence_dust:1>],
  [null, null, null, <ProjectE:item.pe_covalence_dust:2>, <ore:blockBlueGem>, <ProjectE:item.pe_covalence_dust:2>, <ProjectE:item.pe_covalence_dust:1>, <ProjectE:item.pe_covalence_dust:1>, <TConstruct:bowstring>],
  [null, null, <ProjectE:item.pe_covalence_dust:2>, <ore:blockBlueGem>, <ore:blockBlueGem>, <ore:blockBlueGem>, <ProjectE:item.pe_covalence_dust:2>, <TConstruct:bowstring>, <TConstruct:bowstring>],
  [null, <ProjectE:item.pe_covalence_dust>, <ProjectE:item.pe_covalence_dust>, <ProjectE:item.pe_covalence_dust:2>, <ore:blockBlueGem>, <ProjectE:item.pe_covalence_dust:2>, null, <TConstruct:bowstring>, <TConstruct:bowstring>],
  [<ProjectE:item.pe_covalence_dust>, <ore:blockEmerald>, <ore:blockEmerald>, <ProjectE:item.pe_covalence_dust>, <ProjectE:item.pe_covalence_dust:2>, null, null, <TConstruct:bowstring>, <TConstruct:bowstring>],
  [<ProjectE:item.pe_covalence_dust>, <ore:blockEmerald>, <ore:blockEmerald>, <ProjectE:item.pe_covalence_dust>, null, null, null, <TConstruct:bowstring>, <TConstruct:bowstring>],
  [null, <ProjectE:item.pe_covalence_dust>, <ProjectE:item.pe_covalence_dust>, null, null, null, null, <TConstruct:bowstring>, <TConstruct:bowstring>]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:alchemical_chest>,
[[null, null, null, <ProjectE:item.pe_covalence_dust>, <ProjectE:item.pe_covalence_dust:1>, <ProjectE:item.pe_covalence_dust:2>, null, null, null],
  [null, <appliedenergistics2:tile.BlockSkyChest:1>, <appliedenergistics2:tile.BlockSkyChest:1>, <appliedenergistics2:tile.BlockSkyChest:1>, <appliedenergistics2:tile.BlockSkyChest:1>, <appliedenergistics2:tile.BlockSkyChest:1>, <appliedenergistics2:tile.BlockSkyChest:1>, <appliedenergistics2:tile.BlockSkyChest:1>, null],
  [null, <appliedenergistics2:tile.BlockSkyChest:1>, <ExtraPlanets:ingotUranium>, <ore:ingotMithril>, <aether:aercloud:3>, <ore:ingotBlutonium>, <ore:ingotTerrasteel>, <appliedenergistics2:tile.BlockSkyChest:1>, null],
  [<ProjectE:item.pe_covalence_dust>, <appliedenergistics2:tile.BlockSkyChest:1>, <ore:ingotMithril>, <ore:ingotMithril>, <ore:blockLapis>, <ore:ingotBlutonium>, <ore:ingotBlutonium>, <appliedenergistics2:tile.BlockSkyChest:1>, <ProjectE:item.pe_covalence_dust>],
  [<ProjectE:item.pe_covalence_dust:1>, <appliedenergistics2:tile.BlockSkyChest:1>, <ExtraPlanets:ingotUranium>, <ore:blockLapis>, <universalsingularities:universal.tinkersConstruct.singularity:3>, <ore:blockLapis>, <ore:ingotTerrasteel>, <appliedenergistics2:tile.BlockSkyChest:1>, <ProjectE:item.pe_covalence_dust:1>],
  [<ProjectE:item.pe_covalence_dust:2>, <appliedenergistics2:tile.BlockSkyChest:1>, <ore:ingotCyanite>, <ore:ingotCyanite>, <ore:blockLapis>, <magicalcropsarmour:EssenceIngots:2>, <magicalcropsarmour:EssenceIngots:2>, <appliedenergistics2:tile.BlockSkyChest:1>, <ProjectE:item.pe_covalence_dust:2>],
  [null, <appliedenergistics2:tile.BlockSkyChest:1>, <ExtraPlanets:ingotUranium>, <ore:ingotCyanite>, <aether:aercloud:3>, <magicalcropsarmour:EssenceIngots:2>, <ore:ingotTerrasteel>, <appliedenergistics2:tile.BlockSkyChest:1>, null],
  [null, <appliedenergistics2:tile.BlockSkyChest:1>, <OpenBlocks:autoanvil>, <appliedenergistics2:tile.BlockSkyChest:1>, <ExtraUtilities:trashcan>, <appliedenergistics2:tile.BlockSkyChest:1>, <EnderIO:blockVacuumChest>, <appliedenergistics2:tile.BlockSkyChest:1>, null],
  [null, null, null, <ProjectE:item.pe_covalence_dust>, <ProjectE:item.pe_covalence_dust:1>, <ProjectE:item.pe_covalence_dust:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:collector_mk3>,
[[<ore:glowstone>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <ore:glowstone>],
  [<ore:glowstone>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <ore:glowstone>],
  [<ore:glowstone>, <Botania:quartzTypeRed>, <Botania:quartzTypeRed>, <Botania:quartzTypeRed>, <Botania:quartzTypeRed>, <Botania:quartzTypeRed>, <Botania:quartzTypeRed>, <Botania:quartzTypeRed>, <ore:glowstone>],
  [<ore:glowstone>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter:1>, <ProjectE:collector_mk2>, <ExtraPlanets:tile.solar:4>, <ProjectE:collector_mk2>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter>, <ore:glowstone>],
  [<ore:glowstone>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter:1>, <Railcraft:cart.loco.electric>, <ProjectE:collector_mk2>, <Railcraft:signal:12>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter>, <ore:glowstone>],
  [<ore:glowstone>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter:1>, <BuildCraft|Robotics:robot>, <BuildCraft|Robotics:robot>, <BuildCraft|Robotics:robot>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter>, <ore:glowstone>],
  [<ore:glowstone>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter>, <ore:glowstone>],
  [<ore:glowstone>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter>, <ore:glowstone>],
  [<ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:collector_mk2>,
[[null, null, null, null, null, null, null, null, null],
  [null, <ore:glowstone>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <ore:glowstone>, null],
  [null, <ore:glowstone>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <ore:glowstone>, null],
  [null, <ore:glowstone>, <ProjectE:item.pe_matter>, <ProjectE:collector_mk1>, <ExtraPlanets:tile.solar>, <ProjectE:collector_mk1>, <ProjectE:item.pe_matter>, <ore:glowstone>, null],
  [null, <ore:glowstone>, <ProjectE:item.pe_matter>, <MineFactoryReloaded:machine.2:12>, <ProjectE:collector_mk1>, <MineFactoryReloaded:machine.1:9>, <ProjectE:item.pe_matter>, <ore:glowstone>, null],
  [null, <ore:glowstone>, <ProjectE:item.pe_matter>, <ImmersiveEngineering:bullet:8>, <ImmersiveEngineering:bullet:8>, <ImmersiveEngineering:bullet:8>, <ProjectE:item.pe_matter>, <ore:glowstone>, null],
  [null, <ore:glowstone>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter>, <ore:glowstone>, null],
  [null, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, null],
  [null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:collector_mk1>,
[[null, null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null, null],
  [null, null, <ore:glowstone>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <ore:glowstone>, null, null],
  [null, null, <ore:glowstone>, <LogisticsPipes:item.PipeItemsFirewall>, <GalacticraftCore:tile.solar:4>, <GalacticraftMars:tile.marsMachineT2>, <ore:glowstone>, null, null],
  [null, null, <ore:glowstone>, <Railcraft:machine.epsilon:4>, <ironfurnaces:diamond_furnace>, <Railcraft:machine.epsilon:4>, <ore:glowstone>, null, null],
  [null, null, <ore:glowstone>, <enderioaddons:blockTcom>, <enderioaddons:blockTcom>, <enderioaddons:blockTcom>, <ore:glowstone>, null, null],
  [null, null, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, null, null],
  [null, null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.extraTiC.singularity>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.vanilla.singularity:1>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.vanilla.singularity>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.bigReactors.singularity:3>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.bigReactors.singularity:2>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.bigReactors.singularity:1>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.extraPlanets.singularity:4>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.extraPlanets.singularity:3>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.extraPlanets.singularity:2>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);
  
mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.extraPlanets.singularity:1>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.extraPlanets.singularity>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.enderIO.singularity:6>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.enderIO.singularity:5>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.enderIO.singularity:4>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.enderIO.singularity:3>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.enderIO.singularity:2>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_matter:1>,
 [[null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ProjectE:item.pe_matter>, <universalsingularities:universal.enderIO.singularity:1>, <ProjectE:item.pe_matter>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [<ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ExtraPlanets:item.wafer:3>, <ProjectE:item.pe_matter>, <ExtraPlanets:item.wafer:3>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>],
  [null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <ore:gemRedDiamond>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null],
  [null, null, <ProjectE:item.pe_fuel:2>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <evilcraft:garmonbozia>, <ProjectE:item.pe_fuel:2>, null, null],
  [null, null, null, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_fuel:2>, null, null, null]]);
