// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED


// ================================================================================
//#MARKER ADD
mods.avaritia.ExtremeCrafting.addShaped (<minecraft:sponge>,
 [[null, <ExtraPlanets:tile.decorativeBlocks2:4>, null, <ExtraPlanets:tile.decorativeBlocks2:4>, null, <ExtraPlanets:tile.decorativeBlocks2:4>, null, <ExtraPlanets:tile.decorativeBlocks2:4>, null],
  [<ExtraPlanets:tile.decorativeBlocks2:4>, <Thaumcraft:ItemResource:17>, <ExtraPlanets:tile.decorativeBlocks2:4>, <Thaumcraft:ItemResource:17>, <ExtraPlanets:tile.decorativeBlocks2:4>, <Thaumcraft:ItemResource:17>, <ExtraPlanets:tile.decorativeBlocks2:4>, <Thaumcraft:ItemResource:17>, <ExtraPlanets:tile.decorativeBlocks2:4>],
  [null, <ExtraPlanets:tile.decorativeBlocks2:4>, <ore:listAllfishraw>, <MineFactoryReloaded:machine.1:2>, <rftools:liquidAbsorberBlock>, <MineFactoryReloaded:machine.0:7>, <ore:listAllfishraw>, <ExtraPlanets:tile.decorativeBlocks2:4>, null],
  [<ExtraPlanets:tile.decorativeBlocks2:4>, <Thaumcraft:ItemResource:17>, <Botania:prismarine2Stairs>, <Botania:prismarine:2>, <Botania:prismarine:2>, <Botania:prismarine:2>, <Botania:prismarine2Stairs>, <Thaumcraft:ItemResource:17>, <ExtraPlanets:tile.decorativeBlocks2:4>],
  [null, <ExtraPlanets:tile.decorativeBlocks2:4>, <Botania:prismarine:1>, <ThermalExpansion:Sponge:1>, <minecraft:potion:8266>, <ThermalExpansion:Sponge:2>, <Botania:prismarine:1>, <ExtraPlanets:tile.decorativeBlocks2:4>, null],
  [<ExtraPlanets:tile.decorativeBlocks2:4>, <Thaumcraft:ItemResource:17>, <Botania:prismarine>, <Botania:prismarine>, <Botania:prismarine>, <Botania:prismarine>, <Botania:prismarine>, <Thaumcraft:ItemResource:17>, <ExtraPlanets:tile.decorativeBlocks2:4>],
  [null, <ExtraPlanets:tile.decorativeBlocks2:4>, <ore:listAllfishraw>, <MineFactoryReloaded:machine.1:2>, <rftools:liquidAbsorberBlock>, <MineFactoryReloaded:machine.0:7>, <ore:listAllfishraw>, <ExtraPlanets:tile.decorativeBlocks2:4>, null],
  [<ExtraPlanets:tile.decorativeBlocks2:4>, <Thaumcraft:ItemResource:17>, <ExtraPlanets:tile.decorativeBlocks2:4>, <Thaumcraft:ItemResource:17>, <ExtraPlanets:tile.decorativeBlocks2:4>, <Thaumcraft:ItemResource:17>, <ExtraPlanets:tile.decorativeBlocks2:4>, <Thaumcraft:ItemResource:17>, <ExtraPlanets:tile.decorativeBlocks2:4>],
  [null, <ExtraPlanets:tile.decorativeBlocks2:4>, null, <ExtraPlanets:tile.decorativeBlocks2:4>, null, <ExtraPlanets:tile.decorativeBlocks2:4>, null, <ExtraPlanets:tile.decorativeBlocks2:4>, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<avaritiaddons:InfinityChest>,
[[<ore:blockInfinity>, <ore:blockInfinity>, <ore:blockInfinity>, <ore:blockInfinity>, <ore:blockInfinity>, <ore:blockInfinity>, <ore:blockInfinity>, <ore:blockInfinity>, <ore:blockInfinity>],
  [<Avaritia:Resource:6>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <Avaritia:Resource:6>],
  [<Avaritia:Resource:6>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <Avaritia:Resource:6>],
  [<Avaritia:Resource:6>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <ExtraPlanets:ingotUranium>, <JABBA:upgradeCore:9>, <ExtraPlanets:ingotUranium>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <Avaritia:Resource:6>],
  [<Avaritia:Resource:6>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <JABBA:upgradeCore:9>, <avaritiaddons:CompressedChest>, <JABBA:upgradeCore:9>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <Avaritia:Resource:6>],
  [<Avaritia:Resource:6>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <ExtraPlanets:ingotUranium>, <JABBA:upgradeCore:9>, <ExtraPlanets:ingotUranium>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <Avaritia:Resource:6>],
  [<Avaritia:Resource:6>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <Avaritia:Resource:6>],
  [<ore:blockCosmicNeutronium>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <MineFactoryReloaded:machine.1:3>, <ore:blockCosmicNeutronium>],
  [<ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>]]);
  
mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_tome>,
[[null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null],
  [null, null, <ore:ingotInfinity>, <minecraft:experience_bottle>, <magicalcrops:ExperienceEssence>, <magicalcrops:ExperienceEssence>, <magicalcrops:ExperienceEssence>, <magicalcrops:ExperienceEssence>, <ore:ingotInfinity>],
  [null, <ore:ingotInfinity>, <magicalcrops:ExperienceEssence>, <magicalcrops:ExperienceEssence>, <minecraft:written_book>, <universalsingularities:universal.vanilla.singularity:2>, <universalsingularities:universal.bigReactors.singularity:1>, <universalsingularities:universal.bigReactors.singularity>, <magicalcrops:ExperienceEssence>],
  [<ore:ingotInfinity>, <magicalcrops:ExperienceEssence>, <universalsingularities:universal.vanilla.singularity:2>, <cookingbook:recipebook:1>, <thermsingul:ThermalSingularity>, <ore:lexicaBotania>, <magicalcrops:ExperienceEssence>, <magicalcrops:ExperienceEssence>, <universalsingularities:universal.bigReactors.singularity>],
  [<magicalcrops:ExperienceEssence>, <universalsingularities:universal.vanilla.singularity:2>, <thermsingul:ThermalSingularity>, <ImmersiveEngineering:tool:3>, <equivalentenergistics:EMCBook>, <Thaumcraft:ItemThaumonomicon>, <magicalcrops:ExperienceEssence>, <minecraft:experience_bottle>, <magicalcrops:ExperienceEssence>],
  [<ore:ingotInfinity>, <magicalcrops:ExperienceEssence>, <magicalcrops:ExperienceEssence>, <Thaumcraft:ItemEldritchObject:1>, <universalsingularities:universal.general.singularity:14>, <evilcraft:originsOfDarkness>, <magicalcrops:ExperienceEssence>, <ore:ingotInfinity>, <ore:ingotInfinity>],
  [null, <ore:ingotInfinity>, <minecraft:experience_bottle>, <magicalcrops:ExperienceEssence>, <universalsingularities:universal.vanilla.singularity:1>, <magicalcrops:ExperienceEssence>, <ore:ingotInfinity>, null, null],
  [null, <ore:ingotInfinity>, <magicalcrops:ExperienceEssence>, <universalsingularities:universal.enderIO.singularity:4>, <minecraft:enchanted_book>, <magicalcrops:ExperienceEssence>, <ore:ingotInfinity>, null, null],
  [null, null, <ore:ingotInfinity>, <magicalcrops:ExperienceEssence>, <magicalcrops:ExperienceEssence>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ExtraUtilities:creativebuilderswand>,
[[null, null, null, null, null, null, <universalsingularities:universal.extraUtilities.singularity>, null, null],
  [null, null, null, null, null, <universalsingularities:universal.extraUtilities.singularity>, <universalsingularities:universal.extraUtilities.singularity>, <universalsingularities:universal.extraUtilities.singularity>, null],
  [null, null, null, null, <universalsingularities:universal.extraUtilities.singularity>, <universalsingularities:universal.extraUtilities.singularity>, <universalsingularities:universal.extraUtilities.singularity>, <universalsingularities:universal.extraUtilities.singularity>, <universalsingularities:universal.extraUtilities.singularity>],
  [null, null, null, null, null, <universalsingularities:universal.extraUtilities.singularity>, <universalsingularities:universal.extraUtilities.singularity>, <universalsingularities:universal.extraUtilities.singularity>, null],
  [null, null, null, null, <universalsingularities:universal.tinkersConstruct.singularity>, null, <universalsingularities:universal.extraUtilities.singularity>, null, null],
  [null, null, null, <Thaumcraft:WandRod:6>, null, null, null, null, null],
  [null, null, <ExtraUtilities:builderswand>, null, null, null, null, null, null],
  [null, <Thaumcraft:WandRod:6>, null, null, null, null, null, null, null],
  [<TConstruct:toughRod:501>, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:item.pe_mercurial_eye>,
[[null, null, null, null, <evilcraft:condensedBlood>, null, null, null, null],
  [null, null, null, <evilcraft:condensedBlood>, <OpenBlocks:devnull>, <evilcraft:condensedBlood>, null, null, null],
  [null, null, null, <evilcraft:condensedBlood>, <OpenBlocks:devnull>, <evilcraft:condensedBlood>, null, null, null],
  [null, <evilcraft:condensedBlood>, <evilcraft:condensedBlood>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <evilcraft:condensedBlood>, <evilcraft:condensedBlood>, null],
  [<evilcraft:condensedBlood>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <ExtraUtilities:creativebuilderswand>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <evilcraft:condensedBlood>],
  [<evilcraft:condensedBlood>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <Thaumcraft:ItemEldritchObject>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <evilcraft:condensedBlood>],
  [null, <evilcraft:condensedBlood>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <evilcraft:condensedBlood>, null],
  [null, null, <evilcraft:condensedBlood>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <evilcraft:condensedBlood>, null, null],
  [null, null, null, <evilcraft:condensedBlood>, <evilcraft:condensedBlood>, <evilcraft:condensedBlood>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:relay_mk3>,
[[null, null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null, null],
  [null, null, <evilcraft:darkBlock>, <ProjectE:item.pe_matter:1>, <Botania:quartzTypeSunny>, <ProjectE:item.pe_matter:1>, <evilcraft:darkBlock>, null, null],
  [null, null, <evilcraft:darkBlock>, <ProjectE:item.pe_matter>, <Botania:quartzTypeDark>, <ProjectE:item.pe_matter>, <evilcraft:darkBlock>, null, null],
  [null, null, <evilcraft:darkBlock>, <Botania:quartzTypeRed>, <Botania:quartzTypeRed>, <Botania:quartzTypeRed>, <evilcraft:darkBlock>, null, null],
  [null, null, <evilcraft:darkBlock>, <ProjectE:relay_mk2>, <ProjectE:relay_mk2>, <ProjectE:relay_mk2>, <evilcraft:darkBlock>, null, null],
  [null, null, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, null, null],
  [null, null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:relay_mk2>,
[[null, null, null, null, null, null, null, null, null],
  [null, <evilcraft:darkBlock>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <evilcraft:darkBlock>, null],
  [null, <evilcraft:darkBlock>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <Botania:quartzTypeDark>, <evilcraft:darkBlock>, null],
  [null, <evilcraft:darkBlock>, <ProjectE:item.pe_matter:1>, <ProjectE:relay_mk1>, <ThermalDynamics:relay>, <ProjectE:relay_mk1>, <ProjectE:item.pe_matter:1>, <evilcraft:darkBlock>, null],
  [null, <evilcraft:darkBlock>, <ProjectE:item.pe_matter>, <MineFactoryReloaded:cable.redstone:2>, <ProjectE:relay_mk1>, <MineFactoryReloaded:cable.redstone:2>, <ProjectE:item.pe_matter>, <evilcraft:darkBlock>, null],
  [null, <evilcraft:darkBlock>, <ProjectE:item.pe_matter:1>, <ImmersiveEngineering:metalDecoration:9>, <ImmersiveEngineering:metalDecoration:9>, <ImmersiveEngineering:metalDecoration:9>, <ProjectE:item.pe_matter:1>, <evilcraft:darkBlock>, null],
  [null, <evilcraft:darkBlock>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter>, <evilcraft:darkBlock>, null],
  [null, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, null],
  [null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped (<ProjectE:relay_mk1>,
[[<evilcraft:darkBlock>, <Avaritia:Singularity:1>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Botania:quartzTypeSunny>, <Avaritia:Singularity:1>, <evilcraft:darkBlock>],
  [<evilcraft:darkBlock>, <universalsingularities:universal.vanilla.singularity>, <ProjectE:item.pe_matter:1>, <equivalentenergistics:EMCCell>, <equivalentenergistics:EMCCell>, <equivalentenergistics:EMCCell>, <ProjectE:item.pe_matter:1>, <universalsingularities:universal.vanilla.singularity>, <evilcraft:darkBlock>],
  [<evilcraft:darkBlock>, <Avaritia:Singularity:1>, <ProjectE:item.pe_matter>, <equivalentenergistics:EMCCell>, <equivalentenergistics:EMCCell>, <equivalentenergistics:EMCCell>, <ProjectE:item.pe_matter>, <Avaritia:Singularity:1>, <evilcraft:darkBlock>],
  [<evilcraft:darkBlock>, <universalsingularities:universal.vanilla.singularity>, <ProjectE:item.pe_matter:1>, <ExtraUtilities:color_lightgem:15>, <Thaumcraft:blockMetalDevice:2>, <ExtraUtilities:color_lightgem:15>, <ProjectE:item.pe_matter:1>, <universalsingularities:universal.vanilla.singularity>, <evilcraft:darkBlock>],
  [<evilcraft:darkBlock>, <Avaritia:Singularity:1>, <ProjectE:item.pe_matter>, <enderioaddons:blockDrain:1>, <ProjectE:condenser_mk1>, <EnderIO:itemExistingItemFilter>, <ProjectE:item.pe_matter>, <Avaritia:Singularity:1>, <evilcraft:darkBlock>],
  [<evilcraft:darkBlock>, <universalsingularities:universal.vanilla.singularity>, <ProjectE:item.pe_matter:1>, <Botania:pistonRelay>, <Botania:pistonRelay>, <Botania:pistonRelay>, <ProjectE:item.pe_matter:1>, <universalsingularities:universal.vanilla.singularity>, <evilcraft:darkBlock>],
  [<evilcraft:darkBlock>, <Avaritia:Singularity:1>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_matter>, <Avaritia:Singularity:1>, <evilcraft:darkBlock>],
  [<evilcraft:darkBlock>, <universalsingularities:universal.vanilla.singularity>, <Avaritia:Singularity:1>, <universalsingularities:universal.vanilla.singularity>, <Avaritia:Singularity:1>, <universalsingularities:universal.vanilla.singularity>, <Avaritia:Singularity:1>, <universalsingularities:universal.vanilla.singularity>, <evilcraft:darkBlock>],
  [<evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>, <evilcraft:darkBlock>]]);

mods.avaritia.ExtremeCrafting.addShaped (<harvestcraft:chaoscookieItem>,
[[<ExtraUtilities:block_bedrockium>, <ore:nuggetThaumium>, <ore:nuggetVoid>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:nuggetVoid>, <ore:nuggetThaumium>, <ExtraUtilities:block_bedrockium>],
  [<ore:nuggetThaumium>, <ore:nuggetVoid>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:foodRaisincookies>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:nuggetVoid>, <ore:nuggetThaumium>],
  [<ore:nuggetVoid>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:foodRaisincookies>, <ore:foodRaisincookies>, <ore:foodRaisincookies>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:nuggetVoid>],
  [<ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:foodRaisincookies>, <ore:foodRaisincookies>, <minecraft:cookie>, <ore:foodRaisincookies>, <ore:foodRaisincookies>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>],
  [<ore:foodPeanutbuttercookies>, <ore:foodRaisincookies>, <ore:foodRaisincookies>, <minecraft:cookie>, <minecraft:cookie>, <minecraft:cookie>, <ore:foodRaisincookies>, <ore:foodRaisincookies>, <ore:foodPeanutbuttercookies>],
  [<ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:foodRaisincookies>, <ore:foodRaisincookies>, <minecraft:cookie>, <ore:foodRaisincookies>, <ore:foodRaisincookies>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>],
  [<ore:nuggetVoid>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:foodRaisincookies>, <ore:foodRaisincookies>, <ore:foodRaisincookies>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:nuggetVoid>],
  [<ore:nuggetThaumium>, <ore:nuggetVoid>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:foodRaisincookies>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:nuggetVoid>, <ore:nuggetThaumium>],
  [<ExtraUtilities:block_bedrockium>, <ore:nuggetThaumium>, <ore:nuggetVoid>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:foodPeanutbuttercookies>, <ore:nuggetVoid>, <ore:nuggetThaumium>, <ExtraUtilities:block_bedrockium>]]);


// ================================================================================
//#MARKER ADD SHAPELESS


// ================================================================================
//#MARKER ADD SHAPED



