// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE

// ================================================================================
//#MARKER REMOVE SHAPELESS



// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<Avaritia:Resource:1>, [[<Avaritia:Resource>, <ore:itemNetherStar>, <Avaritia:Resource>], [<Avaritia:Resource>, <ore:itemNetherStar>, <Avaritia:Resource>]]);
recipes.removeShaped(<peaether:coinMillBlock>, [[<ore:ingotGold>, null, <ore:ingotGold>], [<ore:ingotIron>, <ProjectE:item.pe_covalence_dust:1>, <ore:ingotIron>], [<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>]]);
recipes.removeShaped(<peaether:coinMillBlock>, [[<ore:ingotGold>, null, <ore:ingotGold>], [<ore:ingotIron>, <ProjectE:item.pe_covalence_dust:2>, <ore:ingotIron>], [<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>]]);
recipes.removeShaped(<peaether:coinMillBlock>, [[<ore:ingotGold>, null, <ore:ingotGold>], [<ore:ingotIron>, <ProjectE:item.pe_covalence_dust>, <ore:ingotIron>], [<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>]]);



// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<ThermalFoundation:material:76> * 9, [<ore:blockEnderium>]);



// ================================================================================
//#MARKER ADD SHAPED
mods.avaritia.ExtremeCrafting.addShaped (<Avaritia:Neutronium_Compressor>, [[<ore:blockSteel>, <ore:blockSteel>, <ore:blockSteel>, <enderioaddons:blockIHopper>, <enderioaddons:blockIHopper>, <enderioaddons:blockIHopper>, <ore:blockSteel>, <ore:blockSteel>, <ore:blockSteel>],
  [<ore:ingotCrystalMatrix>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <ore:ingotCrystalMatrix>],
  [<ore:blockSteel>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <ExtraUtilities:enderCollector>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <ore:blockSteel>],
  [<ore:ingotCrystalMatrix>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <ore:ingotCrystalMatrix>],
  [<Thaumcraft:blockCosmeticSolid:4>, <TConstruct:heavyPlate:500>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <ore:blockCosmicNeutronium>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <TConstruct:heavyPlate:500>, <Thaumcraft:blockCosmeticSolid:4>],
  [<ore:ingotCrystalMatrix>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <ore:ingotCrystalMatrix>],
  [<ore:blockSteel>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <GalacticraftCore:tile.oxygenCollector>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <ore:blockSteel>],
  [<ore:ingotCrystalMatrix>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <OpenBlocks:devnull>, <TConstruct:toughRod:500>, <OpenBlocks:devnull>, <ore:ingotCrystalMatrix>],
  [<ore:blockSteel>, <ore:blockSteel>, <ore:blockSteel>, <ore:ingotCrystalMatrix>, <ore:blockSteel>, <ore:ingotCrystalMatrix>, <ore:blockSteel>, <ore:blockSteel>, <ore:blockSteel>]]);
recipes.addShaped(<Avaritia:Resource:1>, [[<Avaritia:Resource>, <ProjectE:item.pe_klein_star:2>.anyDamage(), <Avaritia:Resource>], [<Avaritia:Resource>, <ProjectE:item.pe_klein_star:2>.anyDamage(), <Avaritia:Resource>]]);
recipes.addShaped(<peaether:coinMillBlock>, [[<ore:compressedBronze>, null, <ore:compressedBronze>], [<aether:zaniteGemstone>, <ProjectE:item.pe_covalence_dust:2>, <aether:zaniteGemstone>], [<ore:compressedBronze>, <ore:compressedBronze>, <ore:compressedBronze>]]);
recipes.addShaped(<peaether:coinMillBlock>, [[<ore:compressedBronze>, null, <ore:compressedBronze>], [<aether:zaniteGemstone>, <ProjectE:item.pe_covalence_dust:1>, <aether:zaniteGemstone>], [<ore:compressedBronze>, <ore:compressedBronze>, <ore:compressedBronze>]]);
recipes.addShaped(<peaether:coinMillBlock>, [[<ore:compressedBronze>, null, <ore:compressedBronze>], [<aether:zaniteGemstone>, <ProjectE:item.pe_covalence_dust>, <aether:zaniteGemstone>], [<ore:compressedBronze>, <ore:compressedBronze>, <ore:compressedBronze>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice:1>, [[<Railcraft:slab:43>, <Railcraft:slab:43>, <Railcraft:slab:43>], [<Railcraft:slab:43>, <EnderIO:itemBasicCapacitor>, <Railcraft:slab:43>], [<ore:slabTreatedWood>, <ore:slabTreatedWood>, <ore:slabTreatedWood>]]);
recipes.addShaped(<aether:obsidianLeggings>, [[<Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>, <Thaumcraft:blockCosmeticSolid:1>], [<Thaumcraft:blockCosmeticSolid:1>, null, <Thaumcraft:blockCosmeticSolid:1>], [<Thaumcraft:blockCosmeticSolid:1>, null, <Thaumcraft:blockCosmeticSolid:1>]]);
recipes.addShaped(<ThermalFoundation:material:76>, [[<ThermalFoundation:material:108>, <ThermalFoundation:material:108>, <ThermalFoundation:material:108>], [<ThermalFoundation:material:108>, <ThermalFoundation:material:108>, <ThermalFoundation:material:108>], [<ThermalFoundation:material:108>, <ThermalFoundation:material:108>, <ThermalFoundation:material:108>]]);
recipes.addShaped(<ThermalFoundation:material:76>, [[<ore:nuggetEnderium>, <ore:nuggetEnderium>, <ore:nuggetEnderium>], [<ore:nuggetEnderium>, <ore:nuggetEnderium>, <ore:nuggetEnderium>], [<ore:nuggetEnderium>, <ore:nuggetEnderium>, <ore:nuggetEnderium>]]);
recipes.addShaped(<ThermalFoundation:material:76>, [[<ore:nuggetEnderium>, <ore:nuggetEnderium>, <ore:nuggetEnderium>], [<ore:nuggetEnderium>, <ore:nuggetEnderium>, <ore:nuggetEnderium>], [<ore:nuggetEnderium>, <ore:nuggetEnderium>, <ore:nuggetEnderium>]]);
recipes.addShaped(<Botania:manaResource:4>, [[<ore:nuggetTerrasteel>, <ore:nuggetTerrasteel>, <ore:nuggetTerrasteel>], [<ore:nuggetTerrasteel>, <ore:nuggetTerrasteel>, <ore:nuggetTerrasteel>], [<ore:nuggetTerrasteel>, <ore:nuggetTerrasteel>, <ore:nuggetTerrasteel>]]);
recipes.addShaped(<ThermalExpansion:Light:2>, [[<ore:ingotLumium>, <ore:ingotLumium>, <ore:ingotLumium>], [<ore:ingotLumium>, <ExtraUtilities:color_redstoneLight>, <ore:ingotLumium>], [<ore:ingotLumium>, <ore:ingotLumium>, <ore:ingotLumium>]]);
recipes.addShaped(<Botania:forestEye>, [[<ore:blockPlatinum>, <Botania:endStoneBrick>, <ore:blockPlatinum>], [<Botania:endStoneBrick>, <OpenBlocks:goldenEye:*>, <Botania:endStoneBrick>], [<ore:blockPlatinum>, <Botania:endStoneBrick>, <ore:blockPlatinum>]]);
recipes.addShaped(<Botania:quartz:3> * 4, [[<ore:ingotQuartz>, <ore:ingotQuartz>, <ore:ingotQuartz>], [<ore:ingotQuartz>, <ore:pearlEnderEye>, <ore:ingotQuartz>], [<ore:ingotQuartz>, <ore:ingotQuartz>, <ore:ingotQuartz>]]);


// ================================================================================
